### ISSUE TITLE
I have installed

### ISSUE THREAD

**Issue by ask2me007** [pluginsGLPI/genericobject#101]
I have installed inventory number auto generation plugin(glpi 0.90) . while creating inventory number using this plugin, the objects created through genericobject is not seen in the inventory number generation  plugin. But in the Generic object management, inventory number plugin is in enabled status.
Is it doesnt support this?

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
