### ISSUE TITLE
You can't assign more than one technician to the same ticket

### ISSUE THREAD

**Issue by fabrizzolla** [pluginsGLPI/genericobject#104]
Scenario:
- Ubuntu Server 14.04 LTS
- GLPI 0.90.3 + Object Management 0.85-1.0

Issue:
- While the Object Mgmt plugin is enabled you are unable to assign more than one technician to the same ticket.
- Disabling the plugin fix the problem automatically, allowing to assign more technicians to the same ticket.

Any help we'll appreciate!

**Comment by fabrizzolla** [comment]
No answers? Too bad... one more piece of information: I've granted full privileges to technicians over the ticket's lifecycle and even like this they're unable to assign their selves or each other in a single ticket. This operation is just possible changing the technician profile to "Super-Admin".

Any help I'll appreciate.

**Comment by wawax** [comment]
Hello,

Are you using other plugins ?
Do you have any errors in debug mode or in logfiles ?

**Comment by fabrizzolla** [comment]
Hi @wawax, thanks for your attention :-)

Yes we're using the following plugins:

- OCSng Inventory 1.2.2: https://github.com/pluginsGLPI/ocsinventoryng
- Dashboard 0.7.5: https://forge.glpi-project.org/projects/dashboard
- Print to PDF 1.0: https://forge.glpi-project.org/projects/pdf

In theory none of it could broke the ticket lifecycle workflow... or not?

Thanks in advance.

**Comment by nsautier** [comment]
hello,
https://github.com/pluginsGLPI/genericobject/pull/111/commits/4446ff74d2fec9a037f98f3285326b4e8e8543f5

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
