### ISSUE TITLE
Forbidden   You don't have permission to access /plugins/genericobject/front/type.php on this server.

### ISSUE THREAD

**Issue by nasry** [pluginsGLPI/genericobject#105]
the plugin is well installed and well activated but the problem is when I try to use it I got Forbidden   You don't have permission to access /plugins/genericobject/front/type.php on this server.
any help please

**Comment by wawax** [comment]
Hello,

Version of GLPi ? Version of the plugin ? OS name & version ?

Thank you

**Comment by trasher** [comment]
Ping @nasry? It looks like a file acls/server configuration issue.

**Comment by trasher** [comment]
Requested infos not provided; closing
