### ISSUE TITLE
Can't to add Model, Type, Category...

### ISSUE THREAD

**Issue by toweroff** [pluginsGLPI/genericobject#108]
Hi
I can add new fields to a new type of object
But I can not add the new values in these fields - I click plus, type the name of the Type (Category, Model ...) and ... nothing
No adds to database and I don't see this in dropdown list
GLPI 0.90.5,  Objects management    0.85-1.2

**Comment by sulian** [comment]
Same problem here. No error message.

In database, perharps an error with the date_creation field ??

**Comment by toweroff** [comment]
I found the workaround - do not use the "isolated" key for field
when "isolated" enabled, the table name generated as correctly first part "glpi_genericplugin_mytype" and concatenated string "genericplugins_mytypes". In one part of table name generate this is correct but not for table and field create. When you try to add new value for the field, generigobject can't add this  because can't find a correct table

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
