### ISSUE TITLE
Problem on upgrade (french)  0.85-1.0 --> 0.85-1.2

### ISSUE THREAD

**Issue by matth974** [pluginsGLPI/genericobject#110]
Bonjour

J'utilisais le plugin Generic Objects v. 0.85-1.0 avec GLPI 0.90.1
Nous prévoyons d'évoluer vers GLPI 9.1 et par conséquent, j'ai installé Generic Objects,  v. 0.85-1.2

Au moment de mettre à jour ce dernier via l'interface GLPI, j'ai le message d'erreur suivant:

> Changement de la structure de la base de donnÃ©es - glpi_plugin_genericobject_types (0 seconde)
> 
> Fatal error: Class 'PluginGenericobjectDiverssmg' not found in /var/www/glpi/plugins/genericobject/inc/type.class.php on line 1926

sachant que Diverssmg correspond à un objet générique créé avec la version du 0.85-1.0 avec GLPI 0.90.1

La migration n'a pas l'air de supporter les objets créés dans la version antérieure.

Que faire?

En vous remerciant.

**Comment by btry** [comment]
Bonjour

J'ai  tenté de reproduire comme suit, mais sans succès
- install d'un GLPi 0.90.1
- install de GenericObject 0.85-1.0
- Création d'un objet générique avec un champ numéro d'inventaire
- mise à jour de Generoc Object vers la dernière révision (version 0.85-1.2)
- clic sur le bouton Upgrade dans la page des plugins

L'upgrade du modèle en base de données semble se passer correctement.

L'objet générique **Diverssmg** existe t il toujours ?
Le fichier **diverssmg.class.php** existe t il dans **glpi/files/_plugins/genericobject/inc/** ?

**Comment by matth974** [comment]
Merci pour ce retour btry.

Effectivement, vous avez bien pointé le problème.

En fait, lors de la migration de notre version de GLPI le répertoire contenant les fichiers n'est pas basculé automatiquement. Ce qui fait que les fichiers sont restés dans le répertoire files de l'ancienne version installée sur notre serveur.

Un copier/coller devrait arranger tout ça.

Merci en tout cas pour votre aide.
