### ISSUE TITLE
use singular instead of plural in object's rightnames

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/genericobject#120]
GLPi uses singular, but the plugin uses plural for the rightnames.

see in #66 a patch proposal by @OscarLoayzaB. However changing the naming convention of the rightnames in the plugin may need some upgrade code. 

see also https://github.com/pluginsGLPI/genericobject/blob/master/inc/object.class.php#L64

**Comment by stonebuzz** [comment]
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
