### ISSUE TITLE
TCPDF ERROR: Some data has already been output, can't send PDF file

### ISSUE THREAD

**Issue by toweroff** [pluginsGLPI/genericobject#121]
Hello

GLPI 9.1 and Genericobject 2.4.0

When I try to export assets list to PDF I got the subject
When Genericobject is disabled, no errors happens

php-errors.log have no any errors

**Comment by satyan01** [comment]
http://forum.glpi-project.org/viewtopic.php?id=54957

**Comment by toweroff** [comment]
I have NO running actions, all actions in "Sheduled" or "Disabled" state

**Comment by toweroff** [comment]
it's worked wor me:

original GLPI_ROOT/inc/search.class.php
`   /**
    * Print generic footer
    *
    * @param $type   display type (0=HTML, 1=Sylk,2=PDF,3=CSV)
    * @param $title  title of file : used for PDF (default '')
    *
    * @return string to display
   **/
   static function showFooter($type, $title="") {

      $out = "";
      switch ($type) {
         case self::PDF_OUTPUT_LANDSCAPE : //pdf
         case self::PDF_OUTPUT_PORTRAIT :
            global $PDF_TABLE;
            if ($type == self::PDF_OUTPUT_LANDSCAPE) {
               $pdf = new GLPIPDF('L', 'mm', 'A4', true, 'UTF-8', false);
            } else {
               $pdf = new GLPIPDF('P', 'mm', 'A4', true, 'UTF-8', false);
            }
`
add a one new line before $PDF_TABLE declaration:
`   /**
    * Print generic footer
    *
    * @param $type   display type (0=HTML, 1=Sylk,2=PDF,3=CSV)
    * @param $title  title of file : used for PDF (default '')
    *
    * @return string to display
   **/
   static function showFooter($type, $title="") {

      $out = "";
      switch ($type) {
         case self::PDF_OUTPUT_LANDSCAPE : //pdf
         case self::PDF_OUTPUT_PORTRAIT :
		ob_end_clean();
            global $PDF_TABLE;
            if ($type == self::PDF_OUTPUT_LANDSCAPE) {
               $pdf = new GLPIPDF('L', 'mm', 'A4', true, 'UTF-8', false);
            } else {
               $pdf = new GLPIPDF('P', 'mm', 'A4', true, 'UTF-8', false);
            }
`
