### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by nicsilvam** [pluginsGLPI/genericobject#123]
I have extarcted the plugin at /usr/share/glpi/plugins and I receive the following error
PHP Fatal error:  Interface 'Zend\\Loader\\SplAutoloader' not found in /usr/share/glpi/plugins/genericobject/inc/autoload.php on line 6 . This makes disappear the login page

**Comment by trasher** [comment]
Which version of GLPI and the plugin?

**Comment by trasher** [comment]
Requested infos not provided, closing.
