### ISSUE TITLE
upgrade to glpi 9.2 failed

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/genericobject#124]
this message appear when i click on install

Change of the database layout - glpi_plugin_genericobject_types (0 seconds)

**Comment by trasher** [comment]
As usual, please provide additional informations...

**Comment by josemine** [comment]
I get the same error, however I have this in my error log "PHP Fatal error:  Class 'PluginGenericobjectChair' not found in /var/www/html/glpi-9.1.2/plugins/genericobject/inc/type.class.php on line 1931" This happens when I try to upgrade generic object to v2.4 using glpi v9.1.2.

**Comment by vrdriver** [comment]
Yep, same stupid issue. Spent a day trying to get this %^$&$ thing working. I did the upgrade to the latest version and I get a message like this:

[30-Mar-2017 05:57:49 GMT] PHP Fatal error:  Class 'PluginGenericobjectAntenna' not found in /var/www/WEBSITE/public_html/glpi/plugins/genericobject/inc/type.class.php on line 1937

**Comment by btry** [comment]
Hi,

@josemine @vrdriver 

You both seem have custom objects declared in your DB, but their autogenerated class files missing.

Check the content of glpi/files/_plugins/genericobject, and see in this subtree your .php files are there.

More info in this PR https://github.com/pluginsGLPI/genericobject/pull/116

**Comment by vrdriver** [comment]
@btry Thanks for that. It helped point me in the right direction. Now to solve another issue where the site doesn't forward when I do a POST of any kind.

**Comment by josemine** [comment]
@btry That did it, thanks

**Comment by btry** [comment]
thank you for your feedbacks
