### ISSUE TITLE
Installation on GLPI 9.1.2

### ISSUE THREAD

**Issue by mleblanc136** [pluginsGLPI/genericobject#129]
Hi, I tried to install generic object 2.4.0 on GLPI 9.1.2 with no luck. I extracted the archive, placed the folder in glpi/plugins/ and named it "genericobject". When I try to install it from the GLPI plugins interface, it gives me an error : 

Changement de la structure de la base de données - glpi_plugin_genericobject_types (0 seconde)

Fatal error: Class 'PluginGenericobjectTablette' not found in /var/www/html/glpi/plugins/genericobject/inc/type.class.php on line 1937

Apache is the owner of the folder "genericobject" and the security is at 777 (recursive).
PHP version is 5.6.25
Centos 7

What can I do to make it work?

Thank you!

**Comment by btry** [comment]
Hi

The missing class looks like a object you created with a previous installation of the plugin.

Are you really installing or are you upgrading it ?

**Comment by mleblanc136** [comment]
I think that back in the days I tried the plugin and then uninstalled it. What I'm doing now is a fresh install of the plugin. Is it possible that the earlier installation broke something ?

**Comment by btry** [comment]
Hi,

I think there ils still data related to your previous installation.

If you want to remove these data, first let's review their state.

Look into jour database if you got some tables with a name beginning with glpi_plugin_genericobject_ .

Look into the directory glpi/files/_plugin/genericobject if there are files.

**Comment by trasher** [comment]
Indeed, what propose @btry should solve your issue. BTW, there is no need at all to set `777`; and apache may not have write access to the plugin directory since data are stored in the GLPI files directory.

**Comment by mleblanc136** [comment]
Hi,

So I deleted the remaining tables in the DB and it did the trick!

Thank you!

**Comment by btry** [comment]
Hi

I said :
> first let's review their state.

This was to know more about the data before doing any deletion, because some tables in GLPI may contain relation to items in the plugin.

Now you actually deleted the data of GenericObject, you might have inconsistencies. Check for example the table glpi_items_tickets. If you got rows containg itemtype LIKE 'PluginGenericobject%', then you have broken relations. Please be careful to not introduce inconsistencies in your database.

**Comment by btry** [comment]
@trasher 

I think this issue could be avoided by #116. Please check it, I updated it.

**Comment by mleblanc136** [comment]
I'm currently work on my "GLPI Test" server so no harm done. Thanks!
