### ISSUE TITLE
Objet générique orphelin suite à la suppression de son entité

### ISSUE THREAD

**Issue by OlivierPDL** [pluginsGLPI/genericobject#134]
Bonsoir,
Il m'est impossible de supprimer un objet générique suite à la suppression de son entité, l'objet est toujours affiché mais l'on ne peut rien faire dessus.
Quelqu'un a-t-il déjà rencontré ce souci et la solution pour y remédier ?
Merci
![erreur_objet_generique_sans_entite](https://cloud.githubusercontent.com/assets/28402746/25717410/ab9a9990-3102-11e7-89df-5caff04c44e9.PNG)

**Comment by btry** [comment]
Bonjour

Si vous êtes sûr que c'est la suppression d'une entité qui cause votre souci, vous pouvez essayer ce qui suit. D'abord dans un environnement de test pour vérifier que ça fonctionne, par prudence :
- créez une ou plusieurs entités pour que l'objet ne soit plus orphelin. Chaque entité créée va avoir pour ID le plus petit nombre non utilisé. Cela fait que les ID sont recyclés.

- essayez de supprimer de  nouveau l'objet.

Si ça fonctionne, ne fermez pas le ticket : il y a un bug à corriger. Mais votre retour d'expérience sera utile.

**Comment by OlivierPDL** [comment]
Bonjour
La création d'une nouvelle entité n'a pas permis de réallouer une entité sur l'objet. L'objet est tjrs orphelin et il est impossible de le sélectionner le message est la suivant : "Vous n'avez pas les droits pour réaliser cette action".
Je suis preneur de vos suggestions
Cordialement,

**Comment by btry** [comment]
Bonjour

À supposer que votre entité a le bon ID, il me semble qu'il faut se déconnecter et se reconnecter pour acquérir les droits sur la nouvelle entité. Réessayez après cette manipulation

**Comment by OlivierPDL** [comment]
Malheureusement cela n'a rien changé

**Comment by btry** [comment]
Je pense qu'il est temps d'examiner côté code et base de données.

Voyez si il y a des erreurs dans php-errors.log et sql-errors.log en lien avec la tentative de suppression.

**Comment by OlivierPDL** [comment]
Bonjour,

Message d'erreur dans le sql-errors.log
 *** MySQL query error:
SQL:
SELECT name AS name
FROM glpi_plugingenericobjectmachines
WHERE id = 174 
 Error: Table 'glpi.glpi_plugingenericobjectmachines' doesn't exist

Je ne vois pas de message d'erreur en lien dans le fichier php-errors.log 

Merci de votre assistance

**Comment by btry** [comment]
Bonjour

Le message est clair: il vous manque une  table dans al base de données.

Arrviez-vous à voir le détail de votre type d'objet ? Si oui je pense que vous devriez créer un objet avec un nom différent, et avec la même configuration. Ensuite, dupliquez la table pour que la copie porte le nom **glpi_plugingenericobjectmachines**. Ensuite essayez de supprimer le type tout juste créé et le type **machine**. 

Faites d'abord le  test sur un GLPI qui peut casser sans risque pour vos utilisateurs.

**Comment by stonebuzz** [comment]
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
