### ISSUE TITLE
is:issue is:open You don't have permission to perform this action

### ISSUE THREAD

**Issue by Zdakman** [pluginsGLPI/genericobject#136]
HI everyone, i have a bug when i activate genericobject plugin, i try to delete assigned Groupe permanently  in ticket, but it show me the worning message "You don't have permission to perform this action".

**Comment by btry** [comment]
Hi

Please provide versions of GLPI and the plugin.

Also check if there are errors in glpi/files/_log, files sql-errors.log and php-errors.log.

**Comment by Zdakman** [comment]
Thanks for your answer, I have glpi 9.1 version and the plugin that make me probleme is objectmanagment.

**Comment by btry** [comment]
Hi

I expected you provide the version of the Generic object, as we already know you're using it.

You did not answered about the log files. Shall I deduce that there is nothing relevant ?

**Comment by Zdakman** [comment]
The plugin change privilege of my users, i resolved the problem by fixing all privilege for all object items that i added, thank you.
