### ISSUE TITLE
Il manque un champ dans la vue personnel

### ISSUE THREAD

**Issue by yann83** [pluginsGLPI/genericobject#138]
bonjour,

Nous utilisons glpi-genericobject-0.84-2.3.3 avec GLPI 0.84.8.
Nous avons un formulaire comportant 11 éléments.
Lorsque nous utilisons la vue personnel pour les afficher les colonnes que l'on souhaite il nous manque un champ.
Lorsque que je desactive "Utiliser Notes" le champ disparu apparaît de nouveau mais un autre champ n'apparaît plus. Le probléme marche en sens inverse lorsque je réctive note.
J'ai essayé de tout recréé à partir de 0 et rien n'y fait, c'est toujours pareil.

**Comment by stonebuzz** [comment]
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
