### ISSUE TITLE
impossible to install

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/genericobject#147]
Hello I have upgraded glpi from 9.1.3 to 9.1.4 and I can't use generic object anymore

I tried to uninstall / clen / install but same issue
$
Change of the database layout - glpi_plugin_genericobject_types (0 seconds)

Fatal error: Uncaught Error: Class 'PluginGenericobjectCreditcard' not found in C:\inetpub\wwwroot\glpi\plugins\genericobject\inc\type.class.php:1937 Stack trace: #0 C:\inetpub\wwwroot\glpi\plugins\genericobject\hook.php(117): PluginGenericobjectType::install(Object(Migration)) #1 C:\inetpub\wwwroot\glpi\inc\plugin.class.php(664): plugin_genericobject_install() #2 C:\inetpub\wwwroot\glpi\front\plugin.form.php(49): Plugin->install('330') #3 {main} thrown in C:\inetpub\wwwroot\glpi\plugins\genericobject\inc\type.class.php on line 1937

**Comment by satyan01** [comment]
solved by copy glpi/files

**Comment by guillermohaad** [comment]
HI @satyan01  
I do not understand your solution? could you explain me?
thank you

**Comment by guillermohaad** [comment]
This solution was the one that helped me, thanks for your help.

---solution--
plugins/genericobject/tools && php check_classes.php.
