### ISSUE TITLE
GLPI 9.2 - Simcard compatibility 

### ISSUE THREAD

**Issue by btry** [pluginsGLPI/genericobject#148]
Simcards moved to the core as a new component

in inc/object.class.php 
```php
         if ($item->canUsePluginSimcard()) {
            if ($plugin->isActivated('simcard') && $plugin->isActivated('simcard')) {
               PluginSimcardSimcard_Item::registerItemtype($class);
            }
         }
```

the code needs an update.

**Comment by stonebuzz** [comment]
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
