### ISSUE TITLE
Issue : enable to remove an assigned tech from a ticket

### ISSUE THREAD

**Issue by cham65** [pluginsGLPI/genericobject#153]
Hi All

We just migrated to GLPI 9.1.6 with plugin Genericobjects 2.4.0.
We have this same issue : not able to remove a technician from a ticket assignment except il we are logged as super admin or when Genericobjects has been inactived.

We had this issue in 0.90.5 but we hope the 9.1.6 could solve it...

Does someone know about a fix about it?

Many thanks

Marie

**Comment by cham65** [comment]
Up !

**Comment by anlifr** [comment]
Bonjour, 

J'ai le même problème et inversement. Si je désactive pas ce plugin je ne peux plus attribuer des techniciens à des tickets.

[](http://forum.glpi-project.org/viewtopic.php?id=159439)

--
Same Problem. I can't attribute tickets to a technician with this plugin.

**Comment by cham65** [comment]
Bonjour

Aprés 3 mois de crise de nerf, voici comment j'ai résolu le pb:
Se connecter en **super admin**
Aller dans la gestion du profil concerné
Onglet **Administration**
Ligne "**Transférer**"  Tout décocher + Sauvegarder + Tout cocher + Sauvegarder
Mêmes actions sur la ligne **Utilisateurs** juste au dessus même onglet, mais je pense que les actions sur **Transferer** suffisent.
Depuis mi septembre on peut à nouveau supprimer et affecter un tech, et le module GENERIC OBJECTS fonctionne parfaitement

A ta dispo 
Si besoin
Cham

****
How I fixed it?
Get connected with Super Admin profile.
Go to the Profile Menu => Administration => Rules => Transfer
unselect all + save + select all + save
Same action on the line Users, but I guess that Transfer is enough
Feel free to ask if further question
Cham

**Comment by anlifr** [comment]
Bonjour,

Merci pour ta solution , mais ça ne fonctionne toujours pas pour moi.
Il faut que dans Configuration-->Gestion d'objet-->Profils , le profil doit avoir tous les droits pour pouvoir fonctionner correctement.Or comme j'ai un profil par service ça va pas si je donne le droit à l'objet crée à tout le monde.
