### ISSUE TITLE
Unable to assign a ticket to a created object

### ISSUE THREAD

**Issue by papacharly974** [pluginsGLPI/genericobject#155]
Unable to assign a ticket to a created object
The object never appears in the list of elements in the creation of the ticket
----
Impossible d'assigner un ticket à un objet créé
L'object n'apparait jamais dans la liste des éléments dans la création du ticket

**Comment by Jean-Christophe-P** [comment]
Idem ICI.
GLPI 9.2.1 / Plugin 2.5.0
"Use Assistance" est bien coché dans les "Behaviours" mais je ne vois pas les objets créés quand je crée un nouveau ticket.

**Comment by ecotex** [comment]
Same issue here...

Associated elements dropdown doesn't have new assets created by this plugin, can anyone help me? Thanks.

**Comment by papacharly974** [comment]
J'ai réussi au final à les faire apparaitre dans les tickets.
Ce n'est donc pas un bug, mais une configuration préalable à appliquer.

J'essaie de retrouver la page du réglage, je ne m'en souviens plus.
Je cherche et reviens ici pour expliquer !

**Comment by ecotex** [comment]
Thanks, Im waiting... Its very important for me.

**Comment by ecotex** [comment]
Ok, find it and solved.

**Comment by arthurrschaefer** [comment]
@ecotex, can you share the path to solve it? Thank you.

**Comment by papacharly974** [comment]
Je reviens (un peu tard désolé ...)
Pour pouvoir assigner un ticket à un nouvel objet il faut : 
1. dans gestion d'objet : cocher associable à un ticket
2. Parc / objet en question : associable à un ticket : oui
3. administration des profil : autoriser le profil concerné à utiliser l'objet
