### ISSUE TITLE
can't assign a group or a user to a ticket when the plugin is enable.

### ISSUE THREAD

**Issue by tlsz1** [pluginsGLPI/genericobject#156]
hi, 
i installed the plugin, and now i can't assign a ticket to a group or a user. when i desable the plugin, i can..

i have glpi 9.1.1 a genericobject 2.4.0

any ideas why?

**Comment by tlsz1** [comment]
i found, i have to active rights to group in plugin's option

**Comment by LordBat** [comment]
Im sorry to revive this post but i have the same issue as you, but i dont know witch group right i need to activate.

Can you put some image or guide me?

Thanks and regards!

**Comment by tlsz1** [comment]
go Administration => Profils , select your profil and at the bottom you have the rights for the plugin.

tell me if its works
