### ISSUE TITLE
Impossible d'ajouter un nouvel objet sur GLPI 9.2

### ISSUE THREAD

**Issue by JeremyPOPIT** [pluginsGLPI/genericobject#157]
Bonjour, 
J'ai installé GLPI 9.2, je voulais tester ce plugin. Je sais qu'il n'a pas été validé pour la 9.2. Est-il prévu pour la 9.2 ? 

Quand je souhaite ajouté un Objet manuellement, je n'ai pas le bouton "sauvegarder".

![image](https://user-images.githubusercontent.com/27486656/31276844-473fb96a-aa9e-11e7-8b82-e3830df5c255.png)

**Comment by cedric-anne** [comment]
Hi,

The 2.5.0 version of this plugin, with GLPI 9.2.x compatibility has been released on december. Can you try to install it and tell us if your problem is resolved ?

Thanks
