### ISSUE TITLE
Installation du plugin sous GLPI 9.2

### ISSUE THREAD

**Issue by jcfigini** [pluginsGLPI/genericobject#158]
Bonjour,

Je ne parviens pas à installer ce plugin sous GLPI 9.2,
une page affiche le message "Changement de la structure de la base de données - glpi_plugin_genericobject_types (1 seconde)" est plus rien ne se passe,

Auriez-vous une idée au sujet de ce problème?

En vous remerciant par avance,

Bien cordialement.

**Comment by trasher** [comment]
Hi,

Please use english; so other cans understand too.

Check your GLPI logs, there may be an error.

**Comment by jcfigini** [comment]
Hi,

I have these errors in the "php-error. log"file:

2017-11-07 15:38:07 [2@SrvInfoBett]
  From Toolbox::deprecated() in /var/www/html/glpi/inc/toolbox.class.php line 477 (0.044", 4.80Mio)
  TableExists() function is deprecated
2017-11-07 15:38:07 [2@SrvInfoBett]
  Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/genericobject/inc/type.class.php:1568      TableExists()
  plugins/genericobject/inc/type.class.php:1927      PluginGenericobjectType::getTypes()
  plugins/genericobject/hook.php:117                 PluginGenericobjectType::install()
  inc/plugin.class.php:730                           plugin_genericobject_install()
  :                                                  Plugin->install()
  front/plugin.form.php:48                           call_user_func()

**Comment by trasher** [comment]
Oh OK.... This plugin in its stable version is not compatible with 9.2 currently. You can try the version from the development branch.

**Comment by jcfigini** [comment]
Thank you for your quick response,
Where can I find the versionfrom the development branch?

**Comment by jcfigini** [comment]
I have find it...
But when i want to update, i have the following error:

Changement de la structure de la base de données - glpi_plugin_genericobject_types (0 seconde)
Unable to load the class PluginGenericobjectApn.You probably have garbage data in your database for this plugin and missing files in /var/www/html/glpi/files/_plugins/genericobject

**Comment by trasher** [comment]
Are files present in the mentioned directory?

**Comment by cedric-anne** [comment]
Hi,

The problem was due to presence of existing objects inside your database for which generated files where missing (maybe not copied during installation of new version).

It should be fixed by #192 .

You can also regenerate files using this command line inside your GLPI directory `cd plugins/genericobject/tools && php check_classes.php` and then install the plugin.

**Comment by cedric-anne** [comment]
Fixed by https://github.com/pluginsGLPI/genericobject/pull/192.
