### ISSUE TITLE
Error on object single and bulk deletion

### ISSUE THREAD

**Issue by xlemuel14** [pluginsGLPI/genericobject#161]
Server returns 500 internal server error on any deletion of object(s).

**Comment by Jean-Christophe-P** [comment]
Came here to that :-)
Same problem for me.
Version 2.4.0 on GLPI 9.2.1

Thanks for the excellent work!
Have a good day

**Comment by Jean-Christophe-P** [comment]
Line 1288 of /genericobject/inc/type.class.php, delete "Bookmark", from the list.
Problem solved.

**Comment by trasher** [comment]
2.4.0 is not compatible with GLPI 9.2. You can try to use develop branch, or wait for a new release.
