### ISSUE TITLE
[feature]Volumes/Components

### ISSUE THREAD

**Issue by dsever** [pluginsGLPI/genericobject#165]
Hi, 

Is is possible to create genericObject that includes other types like Components/Volumes, same as you includes Network using "Use Network connections"?

Thanks
Dubravko

**Comment by stonebuzz** [comment]
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
