### ISSUE TITLE
Generic objects connections

### ISSUE THREAD

**Issue by akhasis** [pluginsGLPI/genericobject#166]
Hello,

I love your plugin, great work!

I'd like to know if I can add the "Connections" tab to a generic object. I can't find the way at the object type configuration, but I can see a boolean field in the database that seems to be a flag for this purpose, which makes me think that I'm doing something wrong.

Thank you!

**Comment by Benchohra** [comment]
Hi, it will be greate to have this option availible

**Comment by stonebuzz** [comment]
This issue hasn't evolved in a long time.
I am closing this issue, feel free to continue the discussion here if you want or reopen it if the problem is still present (with latest version).

Best regards
