### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by elianetusset** [pluginsGLPI/genericobject#169]
Clicking on the Add button in /glpi/plugins/genericobject/front/type.form.php shows the message This page is not working and can not fulfill this request at this time.
HTTP ERROR 500

I'm in version 2.4.0 of the plugin and GLPI in version 9.1.2
Permissions of www.data and 775 have been set to the folder.
Apache service has rebooted as well as rebooted server.

Thank's

**Comment by trasher** [comment]
Check GLPI logs to know what went wrong.

**Comment by elianetusset** [comment]
Good Morning,
Please close the topic, as soon as I perform the update procedure, in case the problem persists, I'll open a new topic.
Thanks,
