### ISSUE TITLE
[2.5.0] Profiles tab on type of objects

### ISSUE THREAD

**Issue by nqb** [pluginsGLPI/genericobject#171]
Hello,

After an upgrade from 2.4.0 to 2.5.0, I notice that all checkboxes in :  `Setup -> Objects management -> My type of objects -> Profiles tab` are unchecked. However, if I select one profile and go on Object Management profile, rights are ok.

Steps to reproduce : upgrade genericobject plugin from 2.4.0 to 2.5.0 with rights on a type of object.

Expected result : you can see rights on your type of object through `Setup -> Objects management -> My type of objects -> Profiles tab`

Actual result : you can't see rights on your type of object through `Setup -> Objects management -> My type of objects -> Profiles tab`

**Comment by cedric-anne** [comment]
Should be fixed by https://github.com/pluginsGLPI/genericobject/issues/182 .

**Comment by cedric-anne** [comment]
Fixed by https://github.com/pluginsGLPI/genericobject/pull/190.
