### ISSUE TITLE
[2.5.0] Multiple locales files with different content

### ISSUE THREAD

**Issue by nqb** [pluginsGLPI/genericobject#174]
Hello,

In [Generic Object documentation](http://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html#edit-labels), we can read this : 

> The plugin creates :
> 
>     a language file for the current language
>     a language file for the default GLPI language

I notice that when French is the current language and English default GLPI language, locales files created looks like that (with a car2 object type) : 
* car2.fr_FR.php
[..]
`$LANG['genericobject']['PluginGenericobjectCar2'][0]="car2";`
* car2.en_GB.php
[..]
`$LANG['genericobject']['car2'][0]="%%NAME%%";`

To my mind : 
* `"%%NAME%%"` should be replace in `car2.en_GB.php`
* `$LANG['genericobject']['car2'][0]` should be replace by `$LANG['genericobject']['PluginGenericobjectCar2'][0]`

Important : if English is the current language and French default GLPI language, same behavior : 
* car2.fr_FR.php
[..]
`$LANG['genericobject']['car2'][0]="%%NAME%%";`
* car2.en_GB.php
[..]
`$LANG['genericobject']['PluginGenericobjectCar2'][0]="car2";`

I didn't see any effect on plugin.

**Comment by cedric-anne** [comment]
Fixed by https://github.com/pluginsGLPI/genericobject/pull/191.
