### ISSUE TITLE
Issue to create a model on datainjection with a genericobject type

### ISSUE THREAD

**Issue by chichtacos** [pluginsGLPI/genericobject#175]
Hi everyone !

I'm using the last versions of these 2 plugins.
Datainjection : 2.5.0
GenericObject 2.5.0
I'm under GLPI version 9.2.1

In datainjection, when I want to create a model with a new type I created with GenericObject (its name is bip), I've got this error on debug mode :

PHP Warning: Declaration of PluginGenericobjectBipInjection::getTable() should be compatible with CommonDBTM::getTable($classname = NULL) in C:\xampp\htdocs\glpi-test\files_plugins\genericobject\inc\bipinjection.class.php at line 36

Datainjection works fine with the natives models (computer, phones, etc..)

Thx a lot for your help !

**Comment by trasher** [comment]
A quick workaround would be to edit the `PluginGenericobjectBipInjection` class file and to change `function getTable()` to `function getTable($classname = null)`.

**Comment by chichtacos** [comment]
Hi,

workaround works fine !

But now, I can't link the fields:
PHP Notice: Undefined index: linkfield in C:\xampp\htdocs\glpi-test\plugins\datainjection\inc\injectiontype.class.php at line 208
PHP Notice: Undefined index: linkfield in C:\xampp\htdocs\glpi-test\plugins\datainjection\inc\injectiontype.class.php at line 280

Do I need to open a new thread (seems to be a different issue)?

Thx a lot !

**Comment by trasher** [comment]
This is indeed a different issue; and this one seems related to datainjection plugin; open another ticket, yes ;)

**Comment by chichtacos** [comment]
Ok I think I can cllose this one.
Link to the new ticket : https://github.com/pluginsGLPI/datainjection/issues/64
