### ISSUE TITLE
##reservation.itemurl## in notification templates doesn't work

### ISSUE THREAD

**Issue by flonou** [pluginsGLPI/genericobject#179]
Hi,

I Created a notification template with the ##reservation.itemurl## tag in the text and it doesn't work for items from generic objects.
The URL is in the form : /glpi/index.php?redirect=PluginGenericobjectType_44
which results in : glpi/plugins/genericobject/front/object.form.php?itemtype=PluginGenericobjectType?id=44&

the ? before id should be a &

**Comment by cedric-anne** [comment]
Hi,

I just made a PR on GLPI core to fix this.

**Comment by cedric-anne** [comment]
Hi,

It will be fixed in next GLPI versions (9.2.4 and 9.3.0).

Regards
