### ISSUE TITLE
Global search doesn't work with GenericObject

### ISSUE THREAD

**Issue by chichtacos** [pluginsGLPI/genericobject#181]
Hi everyone !

I just noticed that when I activate global search on an object created with genericobject : 
![image](https://user-images.githubusercontent.com/36413379/37464349-5c9a2268-2858-11e8-8f5d-bc636539285a.png)

 the "Global" menu on GLPI displays nothing : 

![image](https://user-images.githubusercontent.com/36413379/37464387-7305c8ae-2858-11e8-8d08-e2bfad1a9e19.png)

It came back to normal when I un-select the option on the object.

Thx a lot for your help !

**Comment by cedric-anne** [comment]
Hi,

I tried on GLPI 9.2.3 with GenericObject 2.5.0 and I did not see any difference when I activate the usage of global search for an object.

If you are not using last version of GLPI, can you please try to update and check if problem still exists ?

If you still have the problem, can you check if you have useful logs inside `files/_log/*.log` ?

Thanks

**Comment by chichtacos** [comment]
Hi !

I just updated on 9.2.3 on my test server, and global search is now working with genericobject 2.5.0.

Thx a lot :) !
