### ISSUE TITLE
Problem loading class PluginGenericobjectAccessoire

### ISSUE THREAD

**Issue by baptou60** [pluginsGLPI/genericobject#183]
Hy,

I have a problem after updating GLPI 9.2.1 to 9.2.2.
After installation, I have activate the plugin GenericObject and I have this message :

Impossible de charger la classe PluginGenericobjectAccessoireVous avez probablement d'anciennes données dans votre base pour ce plugin ou des fichiers manquants dans C:\xampp\htdocs\glpi/files/_plugins/genericobject

GLPI 9.2.2
Windows Server 2012R2
XAMP

Help me please...

**Comment by cedric-anne** [comment]
Hi,

This plugin generates php files for each object you create. It seems that files are missing for your object `Accessoire`. To regenerate files for this object. To do this, got to `plugins/genericobject/front/type.php`, then open the form of your object `Accessoire`, then click on `Regenerate files` button that is located inside the `Debug` tab.
