### ISSUE TITLE
Bug updating financial information with massive acctions on 0.85-1.2

### ISSUE THREAD

**Issue by frany88** [pluginsGLPI/genericobject#185]
Im using GLPI 9.1.1 and when I use massive acction the popup said "operation performed propertly" but finantial information is not updated.

Thak you,
FJ Cobo.

**Comment by cedric-anne** [comment]
Hi,

You are using an old version of GLPI and of the plugin. Can you try to update and, if you still have the problem ? If problem is still present, please provide detailed steps to reproduce.

Thanks

**Comment by cedric-anne** [comment]
Hi,

I close this issue as I have no feedback.

Regards
