### ISSUE TITLE
Fatal error: Uncaught Error: Class 'PluginGenericobjectNzmabm' not found

### ISSUE THREAD

**Issue by jerhone** [pluginsGLPI/genericobject#188]
Hi All,

Need help from you guys.

I have installed the latest GLPI version 9.2.3 and installed genericobject plugin using the typical process of installing it. However, I come up with the below error and if I open the webUI it is just a white blank page (see image attached). Please help me with this if I missed something else.

**Error:**

Fatal error: Uncaught Error: Class 'PluginGenericobjectNzmabm' not found
in /var/www/glpi/plugins/genericobject/inc/functions.php:19 Stack trace: #0 /var/www/glpi/plugins/genericobject/inc/commondropdown.class.php(33): dropdown_getTypeName('PluginGenericob...', 0) #1 /var/www/glpi/plugins/genericobject/hook.php(65): PluginGenericobjectCommonDropdown::getTypeName() #2 /var/www/glpi/inc/plugin.class.php(1330): plugin_genericobject_getDropdown(Array) #3 /var/www/glpi/inc/plugin.class.php(1345): Plugin::doOneHook('genericobject', 'plugin_generico...') #4 /var/www/glpi/inc/dropdown.class.php(1043): Plugin::getDropdowns() #5 /var/www/glpi/inc/commondropdown.class.php(111): Dropdown::getStandardDropdownItemTypes() #6 /var/www/glpi/inc/html.class.php(1395): CommonDropdown::getMenuContent() #7 /var/www/glpi/inc/html.class.php(5985): Html::generateMenuSession() #8 /var/www/glpi/inc/html.class.php(1499): Html::displayMainMenu(true, Array) #9 /var/www/glpi/front/central.php(73): Html::header('Standard interf...', '/front/central....' in /var/www/glpi/plugins/genericobject/inc/functions.php on line 19

===============================
**Screen Capture**
![fatal error glpi generic objects plugin](https://user-images.githubusercontent.com/6764347/39685852-6a55a16c-5219-11e8-920b-ff9b14925569.JPG)

**Comment by cedric-anne** [comment]
Hi,

This plugin generates php files for each object you create. It seems that files are missing for your object `Nzmabm`.
1) Verify that GLPI can write inside the `files/_plugins/genericobject/` directory and its childs.
2) Regenerate files for this object. To do this, got to `plugins/genericobject/front/type.php`, then open the form of your object `Nzmabm`, then click on `Regenerate files` button that is located inside the `Debug` tab.

If it does not work, please provide a detailed scenario to reproduce this bug.

**Comment by cedric-anne** [comment]
Hi,

You can also regenerate files using this command line inside your GLPI directory `cd plugins/genericobject/tools && php check_classes.php`.

**Comment by jerhone** [comment]
@cedric-anne I will try this out and update you accordingly. Thanks so much for your reply. I really appreciate it.

Cheers!

**Comment by cedric-anne** [comment]
@jerhone

Have you tried the proposed solution ?

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this issue as I have no feedback about the proposed solution.

Regards

**Comment by guillermohaad** [comment]
thank @cedric-anne 
This solution was the one that helped me, thanks for your help.
