### ISSUE TITLE
enable to create a ticket for a generic object

### ISSUE THREAD

**Issue by cdtx-blum** [pluginsGLPI/genericobject#199]
when a click on "create a ticket" in the field "associated elements" I can't find  the generic object I have created with the plugin.

Thanks
![capture](https://user-images.githubusercontent.com/39723094/40642773-5a1748bc-631e-11e8-9d5f-ca2a91856235.PNG)

**Comment by cedric-anne** [comment]
Hi,

To be able to see your new object type inside this list, you have to update user profile and add this type to `Associable items to a ticket` list. You can do this opening profile form in `Administration > Profiles` and go to the `Assistance` tab.

Regards
