### ISSUE TITLE
Créer des objets en masse

### ISSUE THREAD

**Issue by PlowRaiser** [pluginsGLPI/genericobject#200]
Version GLPI : 9.2.1
Version GenericObject : 2.5.0

Il me semble impossible actuellement de dupliquer un enregistrement pour importer des objets en masse.
Lorsque l'on reçoit 50 pc le but serait de créer un premier object de lui entrer les différentes informations (fabricant fournisseur prix durée de garantie) toute celle qui sont commune pour ensuite le dupliquer 49 fois et venir modifier uniquement son numéro d'inventaire.

Est ce que cela est envisageable ? Existe il une autre façon d'intégrer des objets en masse ?

Merci d'avance.
Cordialement.

**Comment by PlowRaiser** [comment]
Version GLPI : 9.2.1
Version GenericObject : 2.5.0

We would like to duplicate object to import them massively.

Actually we would like to create a first object and add it all the informations that are the same for all PCs like warranty date / price / model etc and then be able to duplicate 49 times this objects. 

After that we would go on each object to set special info like inventory number

Is this actually possible ? Is there any way to create multiple PC or other generic objects like furniture etc ?

Thanks.
Best regards.

**Comment by cedric-anne** [comment]
Hi,

What you want can be done using templates. A template is a preset of value for a given object type that you will be able to choose when creating an object.
![manage_templates](https://user-images.githubusercontent.com/33253653/40769193-a74a3028-64b7-11e8-81bf-b14c6c82934b.png)

For generic objects, you have to enable this feature for each object, in the `Main` tab of the administration page of your object type.

Regards
