### ISSUE TITLE
Plugin does not work in Helpdesk tickets

### ISSUE THREAD

**Issue by jdaruich** [pluginsGLPI/genericobject#204]
I have done these steps.
1) Installed plugin.
2) Created Generic Object category.
3) Created objetcs inside the category.

After doing that catgery does not appear in Helpdesk.
Both category and item have checked helpdesk.

Can anyone help me?

Thanks a lot.
<img width="1320" alt="captura de pantalla 2018-07-09 a la s 22 01 29" src="https://user-images.githubusercontent.com/41029406/42483421-baa7f7e2-83c3-11e8-825c-12d828d9eba7.png">
<img width="1295" alt="captura de pantalla 2018-07-09 a la s 22 01 18" src="https://user-images.githubusercontent.com/41029406/42483424-be720642-83c3-11e8-94ea-be7300346dc4.png">
<img width="1002" alt="captura de pantalla 2018-07-09 a la s 22 00 45" src="https://user-images.githubusercontent.com/41029406/42483428-c27bbeb8-83c3-11e8-8f11-9fedebf6c2b4.png">
<img width="1369" alt="captura de pantalla 2018-07-09 a la s 22 00 21" src="https://user-images.githubusercontent.com/41029406/42483435-c65f206a-83c3-11e8-8019-9e5a72347b4c.png">

**Comment by cedric-anne** [comment]
Hi,

To be able to see your new object type inside this list, you have to update user profile and add this type to `Associable items to a ticket` list. You can do this opening profile form in `Administration > Profiles` and go to the `Assistance` tab.

Regards

**Comment by cedric-anne** [comment]
Duplicates #199.
