### ISSUE TITLE
Illegal String Offset & Global Research

### ISSUE THREAD

**Issue by chichtacos** [pluginsGLPI/genericobject#205]
Hi !

I just updated GLPI on the 9.3.0 version.
So, i also updated Generic Object with the version 2.6.0

In debug mode i can see the following warning : 

PHP Warning: Illegal string offset 'name' in C:\xampp\htdocs\glpi-test\inc\commondbtm.class.php at line 3430
PHP Warning: Illegal string offset 'name' in C:\xampp\htdocs\glpi-test\inc\commondbtm.class.php at line 3437
--

Could you help me solve that please ?
And so the menu : "Parc" => "Global" doesn't work anymore. Nothing appears, like in a previous issue #181 which was resolved by updating the plugin.

Thx a lot!

**Comment by cedric-anne** [comment]
Hi,

You may have additionnal logs in files/_logs/*.log that can help us to find the source of your problem. It looks like you have an orbject that has misconfigured search options. This warning appears at the creation of a logged error when there is a duplication of search options configuration.

Regards

**Comment by chichtacos** [comment]
Hi !

found this on the php-errors.log :  
[2018-08-14 08:39:41] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 657
  *** PHP Warning(2): Illegal string offset 'name'
  Backtrace :
  inc\commondbtm.class.php:3437                      
  inc\search.class.php:5757                          CommonDBTM->searchOptions()
  inc\search.class.php:5564                          Search::getOptions()
  ajax\searchrow.php:50                              Search::getCleanedOptions()
  inc\search.class.php:2179                          include()
  inc\search.class.php:76                            Search::showGenericSearch()
  plugins\genericobject\front\object.php:35          Search::show()
  {"user":"75@VM-SDIS-WEB01","mem_usage":"0.051\", 10.86Mio)"} 
[2018-08-14 08:39:41] glpiphplog.ERROR: CommonDBTM::searchOptions() in C:\xampp\htdocs\glpi\inc\commondbtm.class.php line 3433
Duplicate key 1 (Nom/Nom) in PluginGenericobjectBip searchOptions!  {"user":"75@VM-SDIS-WEB01","mem_usage":"0.001\", 10.86Mio)"} 
[2018-08-14 08:39:41] glpiphplog.ERROR: CommonDBTM::searchOptions() in C:\xampp\htdocs\glpi\inc\commondbtm.class.php line 3433
Duplicate key 86 (Sous-entités/Sous-entités) in PluginGenericobjectBip searchOptions!  {"user":"75@MYSERVERNAME","mem_usage":"0.000\", 10.86Mio)"} 

Hope it can help !

Thx a lot !

**Comment by chichtacos** [comment]
Hi !

found this on the php-errors.log :
[2018-08-14 08:39:41] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 657
*** PHP Warning(2): Illegal string offset 'name'
Backtrace :
inc\commondbtm.class.php:3437
inc\search.class.php:5757 CommonDBTM->searchOptions()
inc\search.class.php:5564 Search::getOptions()
ajax\searchrow.php:50 Search::getCleanedOptions()
inc\search.class.php:2179 include()
inc\search.class.php:76 Search::showGenericSearch()
plugins\genericobject\front\object.php:35 Search::show()
{"user":"75@MYSERVERNAME","mem_usage":"0.051", 10.86Mio)"}
[2018-08-14 08:39:41] glpiphplog.ERROR: CommonDBTM::searchOptions() in C:\xampp\htdocs\glpi\inc\commondbtm.class.php line 3433
Duplicate key 1 (Nom/Nom) in PluginGenericobjectBip searchOptions! {"user":"75@MYSERVERNAME","mem_usage":"0.001", 10.86Mio)"}
[2018-08-14 08:39:41] glpiphplog.ERROR: CommonDBTM::searchOptions() in C:\xampp\htdocs\glpi\inc\commondbtm.class.php line 3433
Duplicate key 86 (Sous-entités/Sous-entités) in PluginGenericobjectBip searchOptions! {"user":"75@MYSERVERNAME","mem_usage":"0.000", 10.86Mio)"}

Hope it can help !

Thx a lot !

**Comment by chichtacos** [comment]
Hi !

sorry I was wokring on other topics :)
My database was corrupted. I completly removed the plugin, reinstalled it and now everything is ok.

This topic can be closed.

Thx for your efforts :)
