### ISSUE TITLE
Default Field Value

### ISSUE THREAD

**Issue by chichtacos** [pluginsGLPI/genericobject#206]
Hello !

First, I searched on old topics if it was already asked by somebody but I didn't find it. 

It's not really an issue, but I would like to know if it's possible to "link" 2 fields together.
My goal is to automatically fill a date field when I enter a date on another.

By example I created a type Vehicule (on which I need to follow some radio parameters) : 
I have a Field 'StartEncryptionDate' = 13-08-2018.
I would like to have the other one 'EndEncryptionDate' automaticaly filled with : 13-08-2020 (two years later)

GLPI 9.3.0
GenericObject 2.6.0

Thx a lot for your time !

**Comment by cedric-anne** [comment]
Hi,

This behaviour does not exists either in this plugins or in Fields plugin. I am not sure it can be done easilly on the current state of both plugins and it seems really specific to this case.
If you want to implement an advanced management of default values, feel free to open a PR (maybe on Fields plugin that already permits definition of default values).

Regards

**Comment by chichtacos** [comment]
Hi ! ok thx a lot for your answer. I'll find another way to rule this case then :)
It can be closed.
Regards
