### ISSUE TITLE
Documentation 2.0 incomplète

### ISSUE THREAD

**Issue by jmreymond** [pluginsGLPI/genericobject#21]
A la lecture de la documentation, 
1. il y manque un point pour faire constant.php
   <glpi root>/plugins/genericobject/fields/constants/<type>.constantphp
2. La doc précise Please note that the file's first line must be the following, otherwise the new fields won't appear in the list:

global $GO_FIELDS, $LANG;
mais il serait bon de préciser qu'il faut d'abord mettre les balises php
<?php  et  ?>

**Comment by trasher** [comment]
Doc has been rewrite; this should be OK now
