### ISSUE TITLE
Missing function getObjectSearchOptions

### ISSUE THREAD

**Issue by loicbenoit** [pluginsGLPI/genericobject#210]
### Steps to reproduce :
1. Create a GenericObject using lastest release (2.6.0)
2. In plugin DataInjection, create a new injection template for your GenericObject.
3. In fields mapping tab, select your object for table.

### Expected result :
Should be able to select an object field to map to CSV field without getting exceptions from plugin GenericObjects.

File "genericobject/inc/object.class.php" should contain method "getObjectSearchOptions()"

### Actual result :
Exception error regarding an undefined method "getObjectSearchOptions()" in my GenericObject.

`Fatal error: Uncaught Error: Call to undefined method PluginGenericobjectFoo::getObjectSearchOptions() in /opt/bitnami/apps/glpi/htdocs/files/_plugins/genericobject/inc/fooinjection.class.php:76
Stack trace:
  #0 /opt/bitnami/apps/glpi/htdocs/plugins/datainjection/inc/injectiontype.class.php(204): PluginGenericobjectFooInjection->getOptions('PluginGenericob...')
  #1 /opt/bitnami/apps/glpi/htdocs/plugins/datainjection/ajax/dropdownChooseField.php(39): PluginDatainjectionInjectionType::dropdownFields(Array)
  #2 {main} thrown in /opt/bitnami/apps/glpi/htdocs/files/_plugins/genericobject/inc/fooinjection.class.php on line 76
`

### Observations
Method found in:
https://github.com/pluginsGLPI/genericobject/blob/change-home-generated-files/inc/object.class.php

Method missing in:
https://github.com/pluginsGLPI/genericobject/blob/master/inc/object.class.php

### GLPI setup:
```
GLPI 9.3.0
PHP 7.1.18
```

**Comment by loicbenoit** [comment]
The function call is located in the objectinjection class template, at line 76:
https://github.com/pluginsGLPI/genericobject/blob/master/objects/objectinjection.class.tpl

**Comment by loicbenoit** [comment]
### Tried
Tested adding this method to file "plugins/genericobject/inc/object.class.php":

/**
    * Backward support for switch from method getObjectSearchOptions to method rawSearchOptions.
    *
    * @param   bool  $with_linkfield   (Optional) Ignored, no backward support.
    *
    * @return  array    A list of search options
    */
   public function getObjectSearchOptions($with_linkfield = false) {
      return $this->rawSearchOptions();
   }

### With result
PHP Notice: Undefined index: linkfield in /opt/bitnami/apps/glpi/htdocs/plugins/datainjection/inc/injectiontype.class.php at lines [212, 219, 284]

**Comment by cedric-anne** [comment]
Hi,

https://github.com/pluginsGLPI/genericobject/pull/211 should fix your problem.
https://github.com/pluginsGLPI/genericobject/pull/212 could be usefull to force regeneration of injection classes when using the `Regenerate files` button in `Debug` tab of your object.

Regards

**Comment by loicbenoit** [comment]
Thanks Cedric_Anne, it's really appreciated! Issue solved.

For posterity, here's what to do:
1- Do **NOT** add method "getObjectSearchOptions" into "plugins/genericobject/inc/object.class.php" as suggested above. This method was just a test and did not help.
2- **Only** add fixes 211 and 212 as suggested by Cedric-Anne.
