### ISSUE TITLE
list of requirements

### ISSUE THREAD

**Issue by joaovitorcavalcante** [pluginsGLPI/genericobject#225]
how do I see the listing of requirements for future plugin updates?

**Comment by cedric-anne** [comment]
Hi,

We are supporting more than last GLPI version only if it is easy to maintain. Current developpement state of plugin is compatible with GLPI 9.3 only.

We will start to work on 9.4 compatibility when 9.4 version will be released in alpha or beta version and will decide at this moment if compatibility with 9.3 could be keeped or not.

Regards
