### ISSUE TITLE
Can't create a new objet

### ISSUE THREAD

**Issue by rcfloresh** [pluginsGLPI/genericobject#233]
I'm trying to create a new object called "token" but I got this error... that's only happen in production environment, in my test environment it's working with out issues.

``PHP Warning: fopen(/opt/glpi/files/_plugins/genericobject/inc/token.class.php): failed to open stream: Permission denied in /opt/glpi/plugins/genericobject/inc/type.class.php at line 1096
PHP Warning: fopen(/opt/glpi/files/_plugins/genericobject/front/token.form.php): failed to open stream: Permission denied in /opt/glpi/plugins/genericobject/inc/type.class.php at line 1096
PHP Warning: fopen(/opt/glpi/files/_plugins/genericobject/front/token.php): failed to open stream: Permission denied in /opt/glpi/plugins/genericobject/inc/type.class.php at line 1096
PHP Warning: mkdir(): Permission denied in /opt/glpi/plugins/genericobject/inc/type.class.php at line 1051
PHP Warning: fopen(/opt/glpi/files/_plugins/genericobject/locales/token/token.en_US.php): failed to open stream: No such file or directory in /opt/glpi/plugins/genericobject/inc/type.class.php at line 1096
PHP Warning: fopen(/opt/glpi/files/_plugins/genericobject/locales/token/token.en_GB.php): failed to open stream: No such file or directory in /opt/glpi/plugins/genericobject/inc/type.class.php at line 1096

Fatal error: Uncaught Error: Class 'PluginGenericobjectToken' not found in /opt/glpi/plugins/genericobject/inc/profile.class.php:305 Stack trace: #0 /opt/glpi/plugins/genericobject/inc/profile.class.php(357): PluginGenericobjectProfile::getTypesRights() #1 /opt/glpi/plugins/genericobject/inc/profile.class.php(340): PluginGenericobjectProfile::changeProfile() #2 /opt/glpi/plugins/genericobject/inc/type.class.php(785): PluginGenericobjectProfile::installRights() #3 /opt/glpi/plugins/genericobject/inc/type.class.php(191): PluginGenericobjectType::addNewObject('token', 'PluginGenericob...', Array) #4 /opt/glpi/inc/commondbtm.class.php(1128): PluginGenericobjectType->post_addItem() #5 /opt/glpi/plugins/genericobject/front/type.form.php(49): CommonDBTM->add(Array) #6 {main} thrown in /opt/glpi/plugins/genericobject/inc/profile.class.php on line 305
``

**Comment by cedric-anne** [comment]
Hi,

The error message says that you webserver does not have rights to create/update files in the `/opt/glpi/files/_plugins/genericobject/inc/` directory.

It is a server configuration issue, not a plugin issue.

Regards
