### ISSUE TITLE
A question - do you plan to release a version compatible with GLPI 9.3.2 soon?

### ISSUE THREAD

**Issue by nsi-test** [pluginsGLPI/genericobject#234]
Take my excuses if I am wrong, but as I see the plugin is not compatible yet to GLPI 9.3.2.
Thanks in advance.

**Comment by cedric-anne** [comment]
Hi,

Where do you see this ?

Latests releases (2.6.x) are compatible with 9.3.x.

Regards

**Comment by nsi-test** [comment]
I am sorry, I omited to share details. In fact on clean installation of GLPI 9.3.2 the plugin installs correctly. But on production GLPI  which is updated form 9.3.0  it says:

Objects management | 2.6.2 | GPLv2+ | Error / to clean | Teclib' & siprossii |   | Yes | Clean

But other plugins like FusionInventory plugin go ok:

FusionInventory | 9.3+1.2 | AGPLv3+ | Enabled | David DURIEUX & FusionInventory team |   | Yes | Disable | Uninstall
![glpi932andplugins](https://user-images.githubusercontent.com/22661676/49086861-3a136f80-f25e-11e8-8b25-1bf572a0fb03.png)

(That picture is not exactly from the production site but it is the same.)

**Comment by nsi-test** [comment]
I am sorry, I omited to share details. In fact on clean installation of GLPI 9.3.2 the plugin installs correctly. But on production GLPI which is updated form 9.3.0 it says:

Objects management | 2.6.2 | GPLv2+ | Error / to clean | Teclib' & siprossii |   | Yes | Clean

But other plugins like FusionInventory plugin go ok:

FusionInventory | 9.3+1.2 | AGPLv3+ | Enabled | David DURIEUX & FusionInventory team |   | Yes | Disable | Uninstall
![glpi932andplugins](https://user-images.githubusercontent.com/22661676/49087142-e05f7500-f25e-11e8-9ffd-c4bb8755ebc1.png)
Picture is not from the production but it is the same.

**Comment by cedric-anne** [comment]
Hi,

It may display this if the plugin state check has been done when plugin directory was not accesible. You can click the "clean" button and then you will be able to "install" and "enable" the plugin.

Cleaning will just clean the state, you should not loose data.

Regards

**Comment by nsi-test** [comment]
Ok, thanks,  I was very afraid to click "Clean", because once I deleted the database data of plugins which was very bad thing, and fortunately we use backups of the virtual machine so - there was no real harm.
I suppose then  I have clicked "Uninstall" and not "Clean". 
In that specific case I have pure test installation (with real data though), so I can try many things.
Thanks Again!
