### ISSUE TITLE
Got duplicated sections in the global serach results page

### ISSUE THREAD

**Issue by ettalhi** [pluginsGLPI/genericobject#239]
When using the following global search fields :
![global_search](https://user-images.githubusercontent.com/29466957/54695226-f3dd6700-4aff-11e9-9869-b67c8142e23b.png)

We get the result page with sections duplicated like follows:
![research_results](https://user-images.githubusercontent.com/29466957/54695225-f3dd6700-4aff-11e9-87f6-2e9184606289.png)

**Comment by stonebuzz** [comment]
Hi @ettalhi 

Can you test this PR -> https://github.com/pluginsGLPI/genericobject/pull/259

this PR fix you problem

Best regards
