### ISSUE TITLE
Outils qui est affiché Outil - Lettre "S" disparaît

### ISSUE THREAD

**Issue by derokk4242** [pluginsGLPI/genericobject#244]
Hello,

My GLPI is version: 9.4.1.1
My plugins is: genericobject 2.7.0

I've found a weird behaviour when I create a new item in Objects Management. 

I created an item called "Outils" but once it is added it loses its S at the end.  I tried with the word "Outilss" and at that moment the two "S" remain.

Got anything about this ?

Best regards,

**Comment by cedric-anne** [comment]
Hi,

This behaviour is here to makes that itemtype be a singular word as GLPI core itemtype management requires it to work properly. To change this, a solution would be to dissociate the itemtype and its label, to be able to have a label that uses special chars, plural form, and that may be changed upon time.

I flag this issue as enhancement.

Regards

**Comment by derokk4242** [comment]
Great hope it get enhanced soon :)

Also if the feature is not already there, don't forget to had a "rename" itemtype with it.

Thank you for your fast answer,

Keep up the great work!

**Comment by benodilo** [comment]
Hello,

I have the same problem. If a create a new object "véhicules", I lose the "s" and the "é".
In assets menu the natives items have "s" in english and french (computer**s**, T**é**l**é**phone**s**, etc)

Best regards.
