### ISSUE TITLE
Creating new fields you create new tables

### ISSUE THREAD

**Issue by ricardocedex** [pluginsGLPI/genericobject#246]
Hello, 

 I´m creating new objects with new fields. I have followed your instructions, and I have realized that when I create a new field, GLPI/GenericObject creates a new table (new object: flowmeter, new field: flow):
```
$GO_FIELDS['plugin_genericobject_flowmeterflows_id']['name']       = __("Flow");
$GO_FIELDS['plugin_genericobject_flowmeterflows_id']['field']      = 'flow';
$GO_FIELDS['plugin_genericobject_flowmeterflows_id']['input_type'] = 'text';
```

GLPI/GenericObject creates a table named "glpi_plugin_genericobject_flowmeterflows". I thought when creating a new field you just create a new column called "flow" in the new object´s table.  This info is not properly explained: https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html#add-new-fields

Is there something I´m doing wrong or is it  bug or something else? Thanks for the help.

**Comment by stonebuzz** [comment]
i @ricardocedex 

your field is a dropdown field or just textfield ?

regarding your declaration, it's a dropdown field (because of 'itemtype_id' part of key)

if you want just a textfield
please refer to -> https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html#add-a-text-field

Best regards

**Comment by ricardocedex** [comment]
Thanks for your answer,


 I just wanted to understand when you create a new field in the same table or when you create a new table for a field. I think now I understand, but newbies will mix both concepts.


Thanks again!

Regards, Ricardo


Ricardo Herrero Santos
Jefe de Área de Ingeniería de Sistemas
CENTRO DE ESTUDIOS HIDROGRÁFICOS - CEDEX
GoogleMaps: https://goo.gl/maps/iRAFNpRqNA8dUVmGA
Paseo Bajo Virgen del Puerto s/n
C.P.: 28005
Teléfono: +34 91 335 80 32
correo: ricardo.herrero@cedex.es<mailto:ricardo.herrero@cedex.es>
________________________________
De: Stanislas <notifications@github.com>
Enviado: viernes, 24 de enero de 2020 11:37:47
Para: pluginsGLPI/genericobject
Cc: Ricardo Herrero Santos; Mention
Asunto: Re: [pluginsGLPI/genericobject] Creating new fields you create new tables (#246)


i @ricardocedex<https://github.com/ricardocedex>

your field is a dropdown field or just textfield ?

regarding your declaration, it's a dropdown field (because of 'itemtype_id' part of key)

if you want just a textfield
please refer to -> https://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html#add-a-text-field

Best regards
