### ISSUE TITLE
Problem when upgrading from 2.5.2 to 2.7.0

### ISSUE THREAD

**Issue by castorsenior** [pluginsGLPI/genericobject#255]
Hello,
When clicking "Activate" in the plugins administration page, we get a white screen. The file log of httpd tels :
*** Error in `/usr/sbin/httpd': free(): invalid pointer: 0x00007f743b094928 ***
Our environment : 
- CentOS 7.7.1908
- Apache 2.4.6
- PHP 7.2 (php72w-common-7.2.24, etc.)
- GLPI 9.2.4 ==> 9.4.4
- Plugin GenericObjects 2.5.2 ==> 2.7.0

Thank you for your attention and your help !
PS : I did the operation which is indicated here (regeneration of the files of the objects created with the plugin) : https://github.com/pluginsGLPI/genericobject/issues/183

**Comment by cedric-anne** [comment]
Hi,

The error seems located in httpd itself. You should try to update Apache, bug may be fixed.

Regards

**Comment by trasher** [comment]
You may try with php-fpm if you currently use mod_php; but thi does ot seems linked to genericobject

**Comment by castorsenior** [comment]
Hi, thank your very much for your so quick answers :-)
I tried with httpd24u-2.4.39-1.ius.centos7.x86_64 and mod_php. The result is unfortunately the same white screen :-(
I need to try now with php-fpm : I'll do it as soon as possible and tell you here what about.
Thanks
With best regards

**Comment by castorsenior** [comment]
Hi, I'm getting still the WSOD (white screen of death), but the logs are speeking now :
[proxy_fcgi:error] [pid 10924] [client 192.168.18.121:40402] AH01067: Failed to read FastCGI header, referer: http://myserver/glpi/front/plugin.php
[proxy_fcgi:error] [pid 10924] (104)Connection reset by peer: [client 192.168.18.121:40402] AH01075: Error dispatching request to : , referer: http://myserver/glpi/front/plugin.php

**Comment by castorsenior** [comment]
Hi, I created an empty glpi database in my 9.2.4 platform with only one object created with the plugin generic objects. The migration to 9.4.4 fails : I'm getting the same white screen when trying to activate the plugin genericobject in the plugins page.

**Comment by stonebuzz** [comment]
Hi @castorsenior 
can you check php-fpm.log when you migrate / activate plugin ?

it looks like a web server configuration problem.

 When apache loads a PHP page using fcgi it sends the request of to PHP-FPM service to be processed. If PHP-FPM takes to long to respond then you will see this type of timeout. 

Plugin migration can take long time, you need to adapt timeout .

Best regards

**Comment by castorsenior** [comment]
Thank you very much Stanislas @stonebuzz  for your answer, very much appreciated :-)))
Yes I tried with PHP-FPM and a recent version of Apache which I specially installed manually. But I didn't touch any paramater in relation with the timeout. Which value would be right ?
I'll make a new test on wednesday.
With best regards

**Comment by stonebuzz** [comment]
Hi @castorsenior 

maybe 
https://stackoverflow.com/questions/40360922/increase-php-fpm-idle-timeout-setting

**Comment by stonebuzz** [comment]
increase value step by step to find the good one, or increase at max, migrate and reduce after.

Best regards

**Comment by castorsenior** [comment]
I'll try that ! Thank you very much :-)

**Comment by castorsenior** [comment]
Hi @stonebuzz 

I'm actually testing. Still the white screen, but I have a mention in the logs : 

**/var/log/php-fpm/error.log**
[29-Jan-2020 12:35:41] WARNING: [pool www] child 63241 exited on signal 6 (SIGABRT) after 560.327063 seconds from start
[29-Jan-2020 12:35:41] NOTICE: [pool www] child 63473 started

**/var/log/php-fpm/www-error.log**
[29-Jan-2020 12:35:41 Europe/Paris] PHP Warning:  Cannot write "/var/www/html/glpi/files/_cache/glpi_cache_db_9.4.5.json" cache footprint file. Cache performance can be lowered. in /var/www/html/glpi/inc/cache/simplecache.class.php on line 223

Here is my file **/etc/httpd/conf.d/php-fpm.conf** :
<VirtualHost _default_:80> 
       DocumentRoot "/var/www/html" 

       <Directory "/var/www/html"> 
               # allow from all 
               Order deny,allow 
               Options FollowSymLinks SymLinksIfOwnerMatch 
               Require all granted 
               AllowOverride All 
               php_admin_value open_basedir /var/www/html 
       </Directory> 

       ErrorLog logs/default-error_log 
       LogLevel warn 
       TransferLog logs/default-access_log 
#       CustomLog logs/default-request_log "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b" 

       SuexecUserGroup apache apache 

       <Proxy "unix:/var/run/php-fpm/default.sock|fcgi://php-fpm"> 
               **ProxySet timeout=300** 
        </Proxy> 

       <FilesMatch \.php$> 
               SetHandler proxy:fcgi://php-fpm 
       </FilesMatch> 
</VirtualHost>

**Comment by stonebuzz** [comment]
Hi @castorsenior 

empty glpi cache folder (/var/www/html/glpi/files/_cache)
verifiy rights (for apache on cache folder)

And retry.

Best regards

**Comment by castorsenior** [comment]
Hi @stonebuzz 
It works :-)  :-)  :-)
I had also to  add the configuration for php-fpm, with the timeout=300, in the /etc/httpd/sites-available/glpi.conf :  
![image](https://user-images.githubusercontent.com/12443836/73358186-5c5baf80-429e-11ea-86b6-c75a252e0491.png)

Thank you very much for your attention and your help ))))
With best regards,
Mikhael.

**Comment by castorsenior** [comment]
PS : do you see a possibility to do this upgrade without php-fpm, on a classical installation of httpd ?

**Comment by stonebuzz** [comment]
from start, problem is cache, i think you can switch to httpd without any problem.

Best regards

**Comment by castorsenior** [comment]
Hi @stonebuzz 

I switched back to httpd, turning off php-fpm. And took care of the repository  _cache.

But it seemed ok : 
![image](https://user-images.githubusercontent.com/12443836/73367133-54583b80-42af-11ea-910b-307cfeca619a.png)

Even after having cleared it completely, the plugin doesn't want to upgrade : I'm landing to the white screen.

Is there somewhere a "timeout" parameter that I can leverage without using php-fpm ?

Thanks a lot, with best regards

**Comment by castorsenior** [comment]
Hi @stonebuzz 

A few hours ago the upgrade worked with the timeout=300.
![image](https://user-images.githubusercontent.com/12443836/73377703-b91b9200-42bf-11ea-865b-b1975b7dfd57.png)
But it was an empty test database with just one object inside, created with GenericObjects.

Now I'm trying to update my real database and it doesn't work... maybe a timeout in FastCgi... I'm searching...

**Comment by castorsenior** [comment]
Hi @stonebuzz 

With my real database I'm getting the white screen after 5 seconds. This time value is lower that all my declared timeouts.

I cleared the directory "_cache" and putted 777 on it.

Still have the same message in /var/log/php-fpm/error.log :+1: 
![image](https://user-images.githubusercontent.com/12443836/73433752-a8adfa80-4345-11ea-8754-069d3fa38980.png)

Thank you for your attention and your help

**Comment by trasher** [comment]
777 is never an option

**Comment by castorsenior** [comment]
That was just for testing ;-)

**Comment by castorsenior** [comment]
Hi @stonebuzz 

I changed the version of PHP : I was with PHP 7.2 and I moved to PHP 7.3. 

The upgrade of Genericobjects works now perfectly.

With best regards
Mikhael.
PS : for the other users, if you want to change PHP version, here you have a tutorial :+1: https://www.tecmint.com/install-php-5-6-on-centos-7/

**Comment by trasher** [comment]
When using CentOS, it's a better idea to rely on the source information (which is up to date),
see: https://rpms.remirepo.net/wizard/
