### ISSUE TITLE
Upgrade GenericObject from GLPI 9.3.0 to GLPI 9.4.4 is KO

### ISSUE THREAD

**Issue by castorsenior** [pluginsGLPI/genericobject#256]
Hello,
When clicking "Activate" in the plugins administration page, we get a white screen. The file log of httpd tells :
*** Error in `/usr/sbin/httpd': free(): invalid pointer: 0x00007f110ba98110 ***
Our environment :
- CentOS 7.7.1908
- Apache 2.4.39 with mod_php
- PHP 7.2 (php72w-common-7.2.24, etc.)
- GLPI 9.3.0 ==> 9.4.4
- Plugin GenericObjects 2.6.2 ==> 2.7.0

We need to update our whole platform to 9.4.4 and we cannot because of this error.
Thank your for your attention and your help !
PS : This issue is linked with https://github.com/pluginsGLPI/genericobject/issues/255 (especially the test with the empty glpi database which is not migrating to 9.4.4 : you can reproduce easily the bug).

**Comment by stonebuzz** [comment]
According to #255

it looks like a web server configuration problem.

use php-fpm and check timeout configuration


When apache loads a PHP page using fcgi it sends the request of to PHP-FPM service to be processed. If PHP-FPM takes to long to respond then you will see this type of timeout.

Plugin migration can take long time, you need to adapt timeout .

Best regards

**Comment by castorsenior** [comment]
Thank you very much Stanislas @stonebuzz  for your answer, very much appreciated :-)))
Yes I tried with PHP-FPM and a recent version of Apache which I specially installed manually. But I didn't touch any paramater in relation with the timeout. Which value would be right ?
With best regards

**Comment by stonebuzz** [comment]
Hi @castorsenior

maybe
https://stackoverflow.com/questions/40360922/increase-php-fpm-idle-timeout-setting

**Comment by stonebuzz** [comment]
Hi @castorsenior have you find solution ?

Best regards

**Comment by castorsenior** [comment]
Hi Stanislas

I reserved a time tomorrow (wednesday) to try this update with a new value
for timeout !

I'll tell you the result !

Thank you very much for taking care :-) ))

With best regards

Le mar. 28 janv. 2020 à 20:26, Stanislas <notifications@github.com> a
écrit :

**Comment by castorsenior** [comment]
Hi @stonebuzz

I changed the version of PHP : I was with PHP 7.2 and I moved to PHP 7.3.

The upgrade of Genericobjects works now perfectly.

With best regards
Mikhael.
PS : for the other users, if you want to change PHP version, here you have a tutorial : https://www.tecmint.com/install-php-5-6-on-centos-7/

**Comment by castorsenior** [comment]
The source information (which is up to date), see: https://rpms.remirepo.net/wizard/
