### ISSUE TITLE
massive modification infocom

### ISSUE THREAD

**Issue by fdthierry** [pluginsGLPI/genericobject#257]
Hi,

I have install GLPI 9.1.6 in Linux server CentOS 7.7 and add plugin genericobject 2.4.0 to manage inventory material.
In ths inventory, I have enabled financial information.

When I want to modify the facture number to many objects with button Actions, Modify, ....
GLPI return message "Success modifying", but the number of facture is not save in the view objects

I have enabled debug mode, but none information and not file php_error.log or sql_error.log generated.

When I execute the same thing in PC Windows, GLPI/plugin same, rights is ok on this folder and I have the error

Without plugin, I have not error when I modify facture number of PC.

Sorry for my approximatly english

Thanks for your response,
bests regards

Merci,
Amicalement,
Thierry

**Comment by trasher** [comment]
You are using very outaded versions of both GLPI and the plugin; please consider updating; and feel free to reopen if the issue still happen.

**Comment by fdthierry** [comment]
Ok, but my server isn't updated PHP 5.4.16 is max on CentOS 7.7 :o(

**Comment by trasher** [comment]
You can use SCL and get maintained PHP version. See https://rpms.remirepo.net/wizard/.

**Comment by fdthierry** [comment]
My System Management service wan't to update CentOS with not official release, sorry

**Comment by fdthierry** [comment]
Sorry, I have install VM with GLPI 9.4.4 and genericobject 2.7.0 and I have the same problem,
I could't update facture number for many object with list and button action.

**Comment by stonebuzz** [comment]
Hi @fdthierry ,
can you test this PR

-> https://github.com/glpi-project/glpi/pull/6826

This PR allow GLPI to update infocom for plugin itemtype (ie : genericobject)

**Comment by fdthierry** [comment]
Goood, it's ok for my old version,

thanks
