### ISSUE TITLE
Install not possible 

### ISSUE THREAD

**Issue by ITfromHell** [pluginsGLPI/genericobject#289]
Hi,

when I´m trying to install genericobject, then I got a blank page when calling "Setup - Plugins".
/var/log/apache2/error.log says: 
 PHP Fatal error:  Uncaught Error: Call to undefined method Plugin::getPhpDir() in /var/www/html/glpi/plugins/genericobject/setup.php:46\nStack trace:\n#0 /var/www/html/glpi/inc/plugin.class.php(316): include_once()\n#1 /var/www/html/glpi/inc/plugin.class.php(318): Plugin->{closure}()\n#2 /var/www/html/glpi/inc/plugin.class.php(287): Plugin->checkPluginState('genericobject')\n#3 /var/www/html/glpi/front/plugin.php(40): Plugin->checkStates(true)\n#4 {main}\n  thrown in /var/www/html/glpi/plugins/genericobject/setup.php on line 46, referer: http://myserver/glpi/front/plugin.php

genericobject 2.9.0
GLPI 9.4.5
PHP 7.2.24-0ubuntu0.18.04.6

Thanks for helping in advance.

**Comment by stonebuzz** [comment]
Hi @ITfromHell 

genericobject 2.9.0 is only compatibl with latest version of GLPI (> 9.5.0)

You need to update your glpi instance.

Best regards
