### ISSUE TITLE
Error 500 during use REST API for generic object access

### ISSUE THREAD

**Issue by VladKozhin** [pluginsGLPI/genericobject#290]
Hello. I have a problem. When I'm trying to get some generic objects with REST API I get 500 error. My request:

`curl -X GET -H 'Content-Type: application/json' -H "Session-Token: 0123456789" -H "App-Token: 0123456789" 'http://glpi-server/glpi/apirest.php/PluginGenericobjectTest' -v`

The GLPI server answer:

```
TCP_NODELAY set
 Expire in 200 ms for 4 (transfer 0x5570cd131f50)
 Connected to glpi-server (310.268.107.257) port 15 (#0)
 GET /glpi/apirest.php/PluginGenericobjectTest HTTP/1.1
 Host: glpi-server
 User-Agent: curl/7.64.0
 Accept: */*
 Content-Type: application/json
 Session-Token: 1234567890
 App-Token: 1234567890
 
 HTTP/1.1 500 Internal Server Error
 Date: Wed, 07 Oct 2020 08:20:03 GMT
 Server: Apache/2.4.37 (centos) OpenSSL/1.1.1c
 X-Powered-By: PHP/7.3.20
 Access-Control-Expose-Headers: content-type, content-range, accept-range
 Expires: Thu, 19 Nov 1981 08:52:00 GMT
 Cache-Control: no-store, no-cache, must-revalidate
 Pragma: no-cache
 Content-Length: 0
 Connection: close
 Content-Type: text/html; charset=UTF-8
 
 Closing connection 0
```

PHP log contains this error:

`[2020-10-07 08:20:03] glpiphplog.ALERT:   *** PHP Compile Error (64): Cannot declare class PluginGenericobjectTest, because the name is already in use in /var/lib/glpi/files/_plugins/genericobject/inc/test.class.php at line 0`

How can I get generic items with REST API?

**Comment by 88ee55** [comment]
rough method
comment strings in file inc/api/api.class.php
`$itemtype = $this->handleDepreciation($itemtype);` 
and comment string in file inc/api/apirest.class.php
```
            // Load namespace for deprecated
            if (Toolbox::isAPIDeprecated($itemtype)) {
               $itemtype = "Glpi\Api\Deprecated\\$itemtype";
            }
```
