### ISSUE TITLE
Error GLPI 9.4.3 - function getPhpDir()

### ISSUE THREAD

**Issue by fbsdev** [pluginsGLPI/genericobject#292]
Hi

The function **getPhpDir()** not exist in GLPI 9.4.3, but the documentation this plugin requires PHP 5.3 or higher **GLPI >= 9.2.**

Fatal error: Uncaught Error: Call to undefined method Plugin::getPhpDir() in /var/www/teste/manutencao/plugins/genericobject/setup.php:46 Stack trace: #0 /var/www/teste/manutencao/inc/plugin.class.php(316): include_once() #1 /var/www/teste/manutencao/inc/plugin.class.php(318): Plugin->{closure}() #2 /var/www/teste/manutencao/inc/plugin.class.php(287): Plugin->checkPluginState() #3 /var/www/teste/manutencao/front/plugin.php(40): Plugin->checkStates() #4 {main} thrown in /var/www/teste/manutencao/plugins/genericobject/setup.php on line 46

Rgs

**Comment by cedric-anne** [comment]
Hi,

Documentation seems not up to date (i.e. `This user manual applies to version 2.5 of the GLPI Generic Object Plugin.`).

Compatibility with GLPI is indicated in [release download page](https://github.com/pluginsGLPI/genericobject/releases).

Regards
