### ISSUE TITLE
Missing ticket images if .constant.php file ends with an empty line.

### ISSUE THREAD

**Issue by J-C-P** [pluginsGLPI/genericobject#299]
All is in the title.
reproductible 100%.
To be tested with a private session of your browser (the cache will hide the bug for a while).
See https://forum.glpi-project.org/viewtopic.php?pid=480963#p480963

**Comment by trasher** [comment]
Full PHP files should not end with `?>`; just ommiting it is a good practice that prevent those kind of issues

**Comment by J-C-P** [comment]
OK, thanks for the update.
The documentation says otherwise...
The exemple file ends with a "?>".
https://glpi-plugins.readthedocs.io/fr/latest/genericobject/#use-case-of-generic-object-as-a-cmms

**Comment by trasher** [comment]
Documentation is wrong then :) You can open a pull request to fix that.

Problem is an empty line after PHP closing tag is considered as output; this typically cause issues with images, PDF, sessions, ... and this may be hard to find why.

I close, this is not a plugin issue.
