### ISSUE TITLE
Internal identifier clips 's' at the end

### ISSUE THREAD

**Issue by RRohi** [pluginsGLPI/genericobject#398]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

10.0,10

### Plugin version

2.14.10

### Bug description

When adding a new Objects management object and entering a name ending with an **s**, after adding the object, the **s** gets removed from the name,

### Steps To reproduce

1. As Administrator, go to `Setup`
2. Go to `Objects management`
3. Click on `+ Add` next to the breadcrumbs on top
4. To `Internal identifier` field enter for examples `Potatoes`
5. Click on `+ Add` on the bottom right.

After saving/adding the object, its name becomes `Potatoe`.

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.10 ( => /Redacted/web/glpi)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux Orion 4.4.302+ #​69057 SMP Thu Jan 25 17:32:36 CST 2024 x86_64
PHP 8.2.21 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bz2, cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter,
	gd, hash, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcntl, pcre, random, readline, session, standard,
	tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="240" memory_limit="128M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: Apache/2.4.58 (Unix) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
Server Software: Source distribution
	Server Version: 10.11.6-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@127.0.0.1:3333/glpi
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.2.21) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.11.6) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
GLPI data directories are located in a secured path.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is not present.
Following extensions are installed: ctype, mbstring.
Following extensions are not present: iconv, sodium.
Write access to /redacted/web/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/redacted/web/glpi"
GLPI_CONFIG_DIR: "/etc/glpi/"
GLPI_VAR_DIR: "/var/lib/glpi"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/redacted/web/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/lib/glpi"
GLPI_CACHE_DIR: "/var/lib/glpi/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/redacted/web/glpi/locales"
GLPI_VERSION: "10.0.10"
GLPI_SCHEMA_VERSION: "10.0.10"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/redacted/web/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/redacted/web/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/redacted/web/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/redacted/web/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/redacted/web/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/redacted/web/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/redacted/web/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/redacted/web/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/redacted/web/glpi/vendor/sabre/http/lib)
sabre/uri in (/redacted/web/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/redacted/web/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/redacted/web/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/redacted/web/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/redacted/web/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/redacted/web/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/redacted/web/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/redacted/web/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/redacted/web/glpi/vendor/symfony/console)
scssphp/scssphp in (/redacted/web/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/redacted/web/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/redacted/web/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/redacted/web/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/redacted/web/glpi/vendor/ramsey/uuid/src)
psr/log in (/redacted/web/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/redacted/web/glpi/vendor/psr/simple-cache/src)
psr/cache in (/redacted/web/glpi/vendor/psr/cache/src)
league/csv in (/redacted/web/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/redacted/web/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/redacted/web/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/redacted/web/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/redacted/web/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/redacted/web/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/redacted/web/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/redacted/web/glpi/vendor/symfony/cache)
html2text/html2text in (/redacted/web/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/redacted/web/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/redacted/web/glpi/vendor/symfony/dom-crawler)
twig/twig in (/redacted/web/glpi/vendor/twig/twig/src)
twig/string-extra in (/redacted/web/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv in (/redacted/web/glpi/vendor/symfony/polyfill-iconv)
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/redacted/web/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/redacted/web/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/redacted/web/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/redacted/web/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldaps://dc.domain.local', Port: '636', BaseDN: 'OU=Redacted,DC=Redacted,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=GLPI
		Searcher,OU=Redacted,DC=Redacted,DC=local', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</pre></details><details><summary>Plugins list</summary><pre> 
	genericobject        Name: Objects management             Version: 2.14.10    State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by stonebuzz** [comment]
Hi @RRohi 

this is how the plugin normally works, to match GLPI's internal framework for naming tables / fields.

Best regards
