### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/genericobject#48]
0.85-1.0
In profile mngt, tab 'Generic objects', 2 wordings - General & Objects - are not translated.
There are not even present in Transifex.

Could you also integrate the spanish translation, available in Transifex.

**Comment by blerohellec** [comment]
Same for 'no types defined yet'. Note it exists the msgid 'No type defined'

**Comment by wawax** [comment]
Synchro with Transifex is due to 0.85+1.1 release

**Comment by blerohellec** [comment]
OK.
Regarding the label " (not types defined yet)", it expects a blank at the beginning of every translation. It's really not obvious at a first glance, and most of translators will fail, resulting in something like that : Objetos(Todavia ningún tipo de objeto definido)
I think that the blank should be added by the program instead.

I updated Transifex for Spanish.
I can do it for French provided you give me the right.
