### ISSUE TITLE
Cannot Open Support Ticket

### ISSUE THREAD

**Issue by enannos** [pluginsGLPI/genericobject#58]
Hi,

the plugin was installed without problems. But when I need to create a ticket, the objects created are not included in the option to choose from the ticket.
The same happens when we need to create a support ticket directly from the object. 
We can choose the ticket field but cannot create a ticket.

**Comment by blerohellec** [comment]
Hello,
To add an instance of a genericobject to a ticket, you must add your GO type to the list of "associable items to a ticket" at profile level : in each profile, go to Assistance tab, paragraph Association, and add your GO type here.
Second, the instance itself must be "Associable to a ticket".

**Comment by ricardocedex** [comment]
This solution should be added in the general info of GO in the example of Biomedical, as I have the same issue and other may have. Thanks for the info! I solved this problem with this message

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
