### ISSUE TITLE
migrating to version 0.85-1.0

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [pluginsGLPI/genericobject#60]
Hello,

i try to migrate the plugin to 0.8.5-1.0 from the 2.3.2 version for glpi 0.8.4.x and i have one custimization for desk chair customisation types.
for that i have files in front:
logistiek.form.php
logistiekmodel.form.php
logistiekmodel.php
logistiek.php

and inc 

logistiek.class.php
logistiekmodel.class.php

and locales/logistiek
logistiek.en_GB.php
logistiek.fr_FR.php

when i try to update the plugin i get this error

Fatal error: Class 'PluginGenericobjectLogistiek' not found in /var/www/glpi/plugins/genericobject/inc/type.class.php on line 1855

i cannot find doc on how to correct this issue

Cheers

**Comment by btry** [comment]
Hi, 

I guess your previous version of the plugin was using the former location for auto-generated classes.

Please check the workaround below on a qualification environment !!

Login in GLPI as a super-admin, navigate through setup > generic object

For each generic type you created : 
  - open it, and go to the tab "debug"
  - click on the button to regenerate files

Your type logistek should be fine now.

**Comment by btry** [comment]
I just noticed the error occurs in the upgrade process, making the workaroud useless.

Move by hands the files of your items in glpi/files/_plugins/genericobjects, reproducing the same directory tree for your original files. Then try to upgrade again.

**Comment by bilbo-the-hobbit** [comment]
Hello,

yes that was it :)

Thank you

**Comment by btry** [comment]
great, but we cannot close the issue right now : the upgrade process should do this for you. ;)

**Comment by bilbo-the-hobbit** [comment]
ho sorry :+1:

**Comment by Giudy** [comment]
Ciao, this solution worked for me as well (migrating to 83.9 to 85.5) but now I get an error whenever I go to an old object created.
If I go to: Asset-<family of the object>-<object>  I get a: You can't acces this page directly
The URL is: /plugins/genericobject/front/<objectfamily>.form.php?id=2

If I create a brand new objectfamily everything works fine. 
but the URL has a different form: /plugins/genericobject/front/object.php?itemtype=PluginGenerator<objectfamily>

in the accesslog I find 401 related errors
WHat can I do?

thanx

davide

**Comment by Giudy** [comment]
Sorry, I've found the debug option and I've regenerated the files but with no change.
What I notice is that whenever I click on it I get an error that says:
Preg_replace(): Compilation failed: a numbered reference must not be zero at offset 17 in ..glpi\plugins\genericobject\inc\functions.php at line 40
I get the same warning if I go to the tab Profiles

**Comment by Giudy** [comment]
Ok, partially solved.
it seems that the regex in the line 40 does not work if the host is windows.
I've replaced the \ with \\

if I go in asset-objectfamily-specific object I get a "you can't access this page directly'

**Comment by Giudy** [comment]
ok, it was a problem with the refresh of the session. it seems that the menus are created when the sessions are created. So now it is fine. now. just added the line to replace the / with the // in the functions.php file.

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
