### ISSUE TITLE
Add possibility to change Label

### ISSUE THREAD

**Issue by neeftarah** [pluginsGLPI/genericobject#63]
Hi,

In current version, the Label is parsed and rename to match object ID on object creation.
The object ID must by rename for technical reason (table name and class name) but Label should not.

Moreover, after creation we can't modify the Label of the object.

**Comment by wawax** [comment]
Hi,

You can modify the label by editing the language file associated to the item

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
