### ISSUE TITLE
technician can't assign ticket to another technician

### ISSUE THREAD

**Issue by magaiverpr** [pluginsGLPI/genericobject#66]
When using the plugin, my technicians can't update the ticket assigning  another technician.

Super-admin works fine.

Specs:

GLPI 0.90
Plugin Version: 0.85-1.0
OS: Debian 7.7

**Comment by btry** [comment]
Hi

Does the issue affect only tickets having a generic object linked to ?

**Comment by magaiverpr** [comment]
No, this error occurs whenever ticket I create, no matter if linking an object created or not.

**Comment by wawax** [comment]
Hello,

Do you have any error in debug mode ? no error also in php-errors or sql-errors log files ?

**Comment by nsautier** [comment]
I have exactly the same problem

GLPI 0.90
Plugin Version: 0.85-1.0
CentOS7 - Mysql

**Comment by nsautier** [comment]
le problème se produit lorsque l'on touche à l'onglet "Profils" dans "Gestion d'Objets"

![capture](https://cloud.githubusercontent.com/assets/11292716/11784145/23ba5e1e-a27b-11e5-9cd3-b745c8824729.PNG)

pour retrouver un comportement normal de GLPI je suis obliger de supprimer l'objet et de le recréer.

toujours rien dans les logs Apache PHP ou SQL

Ma config :
Operating system: Linux serv.fr 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64
PHP 5.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bz2, calendar, ctype, curl, date, dom,
	ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring, mhash, mysql, mysqli,
	openssl, pcre, pdo_mysql, pdo_sqlite, session, shmop, soap, sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="512M" post_max_size="512M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/5.4.16 ()
	Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Server Software: Source distribution
	Server Version: 5.0.95


Libraries

 
htmLawed version 1.1.20 in (/var/www/html/glpi/lib/htmlawed)
phpCas version 1.3.3 in (/var/www/html/glpi/lib/phpcas)
PHPMailer version 5.2.8 in (/var/www/html/glpi/lib/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/html/glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.8 in (/var/www/html/glpi/lib/Zend)
SimplePie version 1.3.1 in (/var/www/html/glpi/lib/simplepie)
TCPDF version 6.2.11 in (/var/www/html/glpi/lib/tcpdf)
ircmaxell/password-compat in (/var/www/html/glpi/lib/password_compat). Compatitility: Ok
 

Plugins list

 
	positions            Name: Cartographie                   Version: 4.2.0      State: Not activated
	formcreator          Name: Formulaires                    Version: 0.90-1.3   State: Enabled
	fusioninventory      Name: FusionInventory                Version: 0.90+1.0   State: Enabled
	genericobject        Name: Gestion d'objets               Version: 0.85-1.0   State: Enabled
	simcard              Name: Gestion de cartes SIM          Version: 1.4.1      State: Enabled
	webservices          Name: Services Web                   Version: 1.6.0      State: Not activated
	dashboard            Name: Tableau de bord                Version: 0.6.9      State: Enabled

**Comment by nsautier** [comment]
Il faut qu' Apache est les droits d’écriture sur les dossiers :
inc/
front/
ajax/
locales/
lors de l'installation du plugins
PB réglé pour moi

**Comment by pcabrera991** [comment]
Same problem here GLPI 0.90.1

**Comment by dethegeek** [comment]
@ french speaking people
@nsautier 
Merci pour le retour

J'ai un patch pour le plugin destiné à changer l'emplacement des fichiers générés. Au lieu d'être dans ```glpi/plugins/genericobject/{inc|ajax|locales|front}``` ces fichiers devraient être répartis de la même manière dans glpi/files/_plugins/genericobject.

Le nouvel emplacement étant normalement accessible en écriture, il devrait y avoir moins de soucis parmi les utilisateurs.

@ englich speaking people
Thanks to nsautier I believe a patch I was working on a few weeks ago may prevent and solve the issue.

The plugin creates php files in glpi/plugins/genericobject/{inc|ajax|locales|front} but this is not the best place. My patch is a try to make the plugin behave better with these files, now saved in ```glpi/files/_plugins/genericobject/...```

After upgrade, all generic objects should be regenerated in the new path. However, the old place is not (yet) cleanedup. The patched version is available here : https://github.com/TECLIB/genericobject/archive/change-home-generated-files.zip

Feedbacks wanted, please, on a *testing* environment.

It the patch succeeds, I expect it will be merged quickly.

**Comment by nsautier** [comment]
bonjour et merci
je vais tester ça rapidement
d'autant que je croyais mon problème réglé mais non.

en fait dès que je crais un objet generic
si un profil d'utilisateur n'a pas tous les droits sur celui-ci, le bug se présente

exemple : j'ai créé l'objet videoprojecteur, le profil Hotliner qui n'a pas accés au parc ni au objet generic provoque une erreur dans la partie assistance(je m'attributs le ticket, je ne peux plus me supprimer des acteurs ni associer un groupe)
![image](https://cloud.githubusercontent.com/assets/11292716/12404018/680f01a4-be38-11e5-9822-15eaae8aea31.png)

par contre si je coche tout les droits sur l'objet generic pour le profil plus de problème

![image](https://cloud.githubusercontent.com/assets/11292716/12403989/30b9d15c-be38-11e5-81ac-5916e09dece2.png)

malheureusement je ne peux me permettre de donner tous les droits sur les objets à tous les profils

**Comment by btry** [comment]
Bonjour,

Alors dans ce cas l'emplacement des fichiers ne doit pas poser de problème, et le patch ne résoudra pas le bug.

Je tenterai de reproduire le bug comme décrit avec le profil hotliner. Je pense que ça permettra de cibler le souci et le corriger.

Le 18 janvier 2016 23:11:44 CET, nsautier <notifications@github.com> a écrit :
>bonjour et merci
>je vais tester ça rapidement
>d'autant que je croyais mon problème réglé mais non.
>
>en fait dès que je crais un objet generic
>si un profil d'utilisateur n'a pas tous les droits sur celui-ci, le bug
>se présente
>
>exemple : j'ai créé l'objet videoprojecteur, le profil Hotliner qui n'a
>pas accés au parc ni au objet generic provoque une erreur dans la
>partie assistance(je m'attributs le ticket, je ne peux plus me
>supprimer des acteurs ni associer un groupe)
>![image](https://cloud.githubusercontent.com/assets/11292716/12404018/680f01a4-be38-11e5-9822-15eaae8aea31.png)
>
>par contre si je coche tout les droits sur l'objet generic pour le
>profil plus de problème
>
>![image](https://cloud.githubusercontent.com/assets/11292716/12403989/30b9d15c-be38-11e5-81ac-5916e09dece2.png)
>
>malheureusement je ne peux me permettre de donner tous les droits sur
>les objets à tous les profils
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/TECLIB/genericobject/issues/66#issuecomment-172667889

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by anthonyberger** [comment]
Bonjour,
je confirme le bug plutôt embetant... j'ai mis un moment a faire le lien,

lorsque le plugin est actf, il n'est plus possible de supprimer l'attribution d'un ticket à une personne ou un groupe : 
"Vous n'avez pas les droits requis pour réaliser cette action."

Tout est ok dès la désactivation du plugin.

ps : L'attribution du ticket reste possible (seulement la suppression d'attribution)

glpi : 0.90
plugin 0.85-1.0

**Comment by OscarLoayzaB** [comment]
Buenos dias,

Al respecto de este incidente aporto una solución que me ha funcionado..
He realizado modificación en las siguientes ficheros:

genericobject/inc/type.class.php
genericobject/inc/object.class.php
genericobject/object/generic.class.tpl

**inc/type.class.php**
Modificacion de la funcion addFileFromTemplate, añadiendo variable ITEMTYPE_RIGHT.

`   
```
public static function addClassFile($name, $classname) {

      self::addFileFromTemplate(array('CLASSNAME' => self::getClassByName($name),

							'ITEMTYPE_RIGHT' => 'plugin_genericobject_'.$name.'s'),

                                self::CLASS_TEMPLATE, GENERICOBJECT_CLASS_PATH, $name.".class");

   }
```
   `
**inc/object.class.php**
Comentar la linea de abajo con self::$rightname del metodo __construct

               //self::$rightname = 'plugin_genericobject_'.strtolower($results[1]).'s';
			   
**object/generic.class.tpl**
Añadir a la plantilla para generar object class la variable ITEMTYPE_RIGHT.

```
class %%CLASSNAME%% extends PluginGenericobjectObject {

   static $rightname = '%%ITEMTYPE_RIGHT%%';
   
   static function getFormURL($full=true) {
      return Toolbox::getItemTypeFormURL( get_parent_class() , $full) .
      "?itemtype=".get_called_class();
   }
   static function getSearchURL($full=true) {
      return Toolbox::getItemTypeSearchURL( get_parent_class() , $full) .
      "?itemtype=".get_called_class();

   }
}
```

Para que los cambios tengan efecto se recomienda instalar y activar el plugin genericobject.
Luego crear objetos y probar que no haya conflictos con los permisos con otros objetos del core de glpi.

Saludos.

**Comment by abriuschi** [comment]
Hola @OscarLoayzaB , he implementado la solución que indicas y me funciona parcialmente. Te comento, cuando intento asignar un grupo/tecnico a cualquier ticket, utilizando los combos con las opciones, me genera el error:

Fatal error: Class '' not found in /data/www/glpi/plugins/genericobject/inc/object.class.php on line 766

En cambio, si utilizo el botón para autoasignarse al ticket, funciona perfectamente.

Además, quitar un grupo/técnico asignado al ticket, funciona perfectamente.

Si me podrías ayudar, te lo agradezco.
Saludos.-

**Comment by OscarLoayzaB** [comment]
Hola,
Vamos a intentarlo, aunque es la primera vez que participo por aquí.
Intenta probar si te funciona en un entorno unicamente con el
coreGlpi+GenericObject activado, tendrías que desactivar otros plugins,
(esto por si hay interferencia).
En todo caso, puedes indicarme que es lo que pone en esa línea. 766.
Que versiones de Glpi y genericobject usas?
Un saludo.

El 24 de febrero de 2016, 15:45, abriuschi <notifications@github.com>
escribió:

> Hola @OscarLoayzaB <https://github.com/OscarLoayzaB> , he implementado la
> solución que indicas y me funciona parcialmente. Te comento, cuando intento
> asignar un grupo/tecnico a cualquier ticket, utilizando los combos con las
> opciones, me genera el error:
>
> Fatal error: Class '' not found in
> /data/www/glpi/plugins/genericobject/inc/object.class.php on line 766
>
> En cambio, si utilizo el botón para autoasignarse al ticket, funciona
> perfectamente.
>
> Además, quitar un grupo/técnico asignado al ticket, funciona perfectamente.
>
> Si me podrías ayudar, te lo agradezco.
> Saludos.-
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TECLIB/genericobject/issues/66#issuecomment-188284124>
> .
>



-- 
Oscar Loayza B.
-----------------------
Murcia - Spain

**Comment by abriuschi** [comment]
Hola @OscarLoayzaB Gracias por la respuesta.
Te cuento, actualmente tengo instalada la versión 0.85.5 de GLPI. La actualicé el día de ayer.
Además, tengo instalada la versión 0.85-1.0 de genericObject. Conjuntamente, el otro plugin que está instalado es el OCS Inventory NG en su versión 1.1.2.
Para hacer la prueba, deshabilité el plugin OCS Inventory, luego intenté hacer las mismas operaciones que generan error. El problema se mantiene.

En cuanto a la línea del error, esto es lo que dice:

`$item = new $this->objecttype->fields['itemtype'];`

Aparentemente esto: $this->objecttype->fields['itemtype'] viene vacío. Si valido el contenido de esto y no instancio el objeto cuando no tiene valor, luego da error porque lo quiere usar y no está instanciado el objeto. 

Agradezco que te tomes el tiempo en ayudarme.
Saludos.-

**Comment by OscarLoayzaB** [comment]
Para empezar yo tengo la misma versión de GenericObject que usas.
En cuanto al core de GLPI yo tengo instalado sobre el 0.85.5 + BugFixes (
https://github.com/glpi-project/glpi/tree/0.85/bugfixes) que no es lo mismo
que el release.

También se me ocurre en esa linea (que yo la tengo igual).
$item = new $this->objecttype->fields['itemtype'];

Se tenga que forzar poniendo:
$item = new $this->objecttype->fields['itemtype']();

Que versión de Apache o PHP tienes.



El 24 de febrero de 2016, 17:58, abriuschi <notifications@github.com>
escribió:

> Hola @OscarLoayzaB <https://github.com/OscarLoayzaB> Gracias por la
> respuesta.
> Te cuento, actualmente tengo instalada la versión 0.85.5 de GLPI. La
> actualicé el día de ayer.
> Además, tengo instalada la versión 0.85-1.0 de genericObject.
> Conjuntamente, el otro plugin que está instalado es el OCS Inventory NG en
> su versión 1.1.2.
> Para hacer la prueba, deshabilité el plugin OCS Inventory, luego intenté
> hacer las mismas operaciones que generan error. El problema se mantiene.
>
> En cuanto a la línea del error, esto es lo que dice:
>
> $item = new $this->objecttype->fields['itemtype'];
>
> Aparentemente esto: $this->objecttype->fields['itemtype'] viene vacío. Si
> valido el contenido de esto y no instancio el objeto cuando no tiene valor,
> luego da error porque lo quiere usar y no está instanciado el objeto.
>
> Agradezco que te tomes el tiempo en ayudarme.
> Saludos.-
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TECLIB/genericobject/issues/66#issuecomment-188352485>
> .
>



-- 
Oscar Loayza B.
-----------------------
Murcia - Spain

**Comment by abriuschi** [comment]
@OscarLoayzaB
Gracias nuevamente.

Yo tengo el último release que está publicado en la web oficial de GLPI.
Tal vez debería intentar instalar los bugfixes. 
También intentaré el cambio en la línea que te comentaba.

Está todo montado sobre un Debian 64 bit+Apache/2.2.22+PHP 5.4.45

Intento con los bugfixes y comento!
Muchas gracias desde ya!
Saludos.-

**Comment by abriuschi** [comment]
Hola @OscarLoayzaB . Te comento los avances. 

He instaldo el bugfixes. El inconveniente persiste pero con los tickets que tienen asignado algún elemento que haya creado con este plugin. Es decir, si el ticket tiene algún elemento que yo he creado, genera error al asignar manualmente un grupo o técnico. De igual manera, cuando vuelvo a entrar al ticket la operación la realizó. Al eliminar un grupo o técnico no tengo inconvenientes. Avisame si no he sido claro con mi comentario.

En cuanto a la modificación de la línea, no la he probado aún. Pero el inconveniente es que viene vacío esto: $this->objecttype->fields['itemtype']

Se te ocurre algo más?

Muchísimas gracias por la ayuda!
Saludos.-

**Comment by OscarLoayzaB** [comment]
Hola,

He intentado reproducir lo que me indicas, pero no he encontrado la manera
de que me salga el error que te aparece.
Como se que ya tienes la configuración de GLPI que tengo yo, me he puesto a
comparar el genericobject con la version de la clase Object.class.php
respecto a la que tienes descargada del release 0.85.+1.0.
Te comento que yo hice algunas modificaciones personalizadas en esta clase
para el proyecto.
Quizas la diferencia mas llamativa que encontre es la siguiente linea 64.
//self::$rightname = 'plugin_genericobject_'.strtolower($results[1]).'s';
Yo la tengo comentada, puesto que influye en los permisos.

Puedes a ver la prueba a ver si hay suerte.

Un saludo.



El 25 de febrero de 2016, 13:39, Alejandro B <notifications@github.com>
escribió:

> Hola @OscarLoayzaB <https://github.com/OscarLoayzaB> . Te comento los
> avances.
>
> He instaldo el bugfixes. El inconveniente persiste pero con los tickets
> que tienen asignado algún elemento que haya creado con este plugin. Es
> decir, si el ticket tiene algún elemento que yo he creado, genera error al
> asignar manualmente un grupo o técnico. De igual manera, cuando vuelvo a
> entrar al ticket la operación la realizó. Al eliminar un grupo o técnico no
> tengo inconvenientes. Avisame si no he sido claro con mi comentario.
>
> En cuanto a la modificación de la línea, no la he probado aún. Pero el
> inconveniente es que viene vacío esto: $this->objecttype->fields['itemtype']
>
> Se te ocurre algo más?
>
> Muchísimas gracias por la ayuda!
> Saludos.-
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TECLIB/genericobject/issues/66#issuecomment-188768398>
> .
>



-- 
Oscar Loayza B.
-----------------------
Murcia - Spain

**Comment by abriuschi** [comment]
Hola @OscarLoayzaB 
Muchas gracias por la respuesta. Esa línea ya la tengo comentada ya que es el cambio que sugerías más arriba.

Bueno, estuve haciendo pruebas y te cuento que he detectado.
Generé un tipo de objeto nuevo y agregue uno en forma manual.
Lo relacioné a un ticket, agregué un grupo, lo eliminé. Todo sin problemas.

Ahora bien. En la migración de versión, tuve que desinstalar el plugin generic object, (venía de GLPI 0.84.8), ya que al intentar migrar no lograba que funcione. Por este motivo, actualicé GLPI, luego instale la nueva versión de generic Object, creé los objetos que necesitaba, e hice un insert directamente en las tablas. 
Con esto recuperé los objectos que tenía cargado y no perdí la historia. Pero me ha quedado este inconveniente.

Voy a seguir probando para ver si llego a alguna solución. Pero crear y cargar todo de nuevo va a ser complicado ya que debe coincidir los IDs para no perder las relaciones anteriores. 

Muchas gracias por ayudarme!!

Saludos.-

**Comment by magaiverpr** [comment]
@dethegeek Works fine to me!!! Thanks! Plx make a pull request to this fix!


@wawax me can merge this?

**Comment by wawax** [comment]
Hi. Could you validate that everyting is ok now on master branch ?

thank you

**Comment by trasher** [comment]
This issue should be fixed in the latest release (0.85-1.1). Feel free to reopen the ticket if the problem still persists.

**Comment by magaiverpr** [comment]
Sorry for the delay.

Updated to version 0.85-1.2 but problem persist.

**Comment by trasher** [comment]
@dethegeek could you please check if you patch has been merged? I guess it was... But seems I was wrong.

**Comment by dethegeek** [comment]
Hi

The patch has not been merged as far as I know, and as found in the logs (see green branch)

![image](https://cloud.githubusercontent.com/assets/5788361/20218711/2f5062b2-a826-11e6-86ff-eb39407a000e.png)

However, I remember I saw similar work in the master branch a few days or weeks later I started mine. 

As the files are now in the good place, when running the master branch, mine should be deleted : it is obsolete.

However, the bug in this ticket seems not solved.

**Comment by btry** [comment]
Hi 

While re-reading this ticket I notice the problem is related to rights. I'm especially interested by the post @OscarLoayzaB . I don't speak his language, but as far as I understand, his patch seems close the solution I provided in #119 which seems to solve #114 

I'm suspecting this ticket and #114 are duplicates.

**Comment by btry** [comment]
Hi

@magaiverpr : The fix for #114 has been merged. Can you check it also solve your issue ? Don't forget to refresh the class files as described in #114. If you miss this step, the bug will persist.

**Comment by btry** [comment]
PR #119 fixes #114, which is a duplicate if this issue.
