### ISSUE TITLE
Can I set the multi-byte string in the label?

### ISSUE THREAD

**Issue by novaoki** [pluginsGLPI/genericobject#69]
Hi.
Can I set the multi-byte string in the label?
For example, Is it possible to set the Japanese label?
What do I need to set procedure?
I English is not well.
Thanks.

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
