### ISSUE TITLE
Upgrade fails:  glpi_plugin_genericobject_types (2 seconds)

### ISSUE THREAD

**Issue by janpieters74** [pluginsGLPI/genericobject#72]
Hello

I just upgraded the pluging in GLPI version 0.90.1 from version 2.3.2 to version 0.85-1.0.
After clicking the 'upgrade button I get following message in my blank browser screen. And it stays there forever. What causes this ?

>> wijziging van de database opmaak - glpi_plugin_genericobject_types (2 seconds)

Please can someone help ?

Kind regards,
Jan

**Comment by btry** [comment]
Hi,

Can you translate the error message in english please ? Also, there is maybe some useful errors in sqlèerrors.log and php-errors.log (in glpi/files/_log/ )

**Comment by janpieters74** [comment]
Translation is: Change of database layout

**Comment by btry** [comment]
Unfortunately, this message is not explicit about your issue. Any log in the above mentioned files ?

**Comment by janpieters74** [comment]
At This moment I'm on the move. I can not verify the log files, but It seems to me there was something wrong with the update proces with respect to the object types

**Comment by janpieters74** [comment]
Hi

I checked: Not one single line mentioned in those logfiles

Regards
Jan

-----Oorspronkelijk bericht-----
Van: "btry" <notifications@github.com>
Verzonden: ‎8/‎01/‎2016 18:04
Aan: "TECLIB/genericobject" <genericobject@noreply.github.com>
CC: "janpieters74" <jan.pieters@gmail.com>
Onderwerp: Re: [genericobject] Upgrade fails:  glpi_plugin_genericobject_types(2 seconds) (#72)

Unfortunately, this message is not explicit about your issue. Any log in the above mentioned files ?

**Comment by btry** [comment]
Hi

Then there is probably a fatal error. I think you will find a log entry with a backtrace in your error log of your HTTP server. Can you check here please ?

**Comment by janpieters74** [comment]
Dear

I fixed by completely removing the pluging (also on DB level), reinstalling the pluging and restoring the object tables.

So you can close the issue...

Regards 
Jan

-----Oorspronkelijk bericht-----
Van: "btry" <notifications@github.com>
Verzonden: ‎9/‎01/‎2016 9:00
Aan: "TECLIB/genericobject" <genericobject@noreply.github.com>
CC: "janpieters74" <jan.pieters@gmail.com>
Onderwerp: Re: [genericobject] Upgrade fails:  glpi_plugin_genericobject_types(2 seconds) (#72)

Hi
Then there is probably a fatal error. I think you will find a log entry with a backtrace in your error log of your HTTP server. Can you check here please ?

**Comment by btry** [comment]
Can you anyway check the HTTP server log ? There is proably something to do to make a stronger code.

**Comment by janpieters74** [comment]
After removing the plugin, and rëinstalling te pluging (also restoring data directly to tables) I receive following error shows up at php-errors.log:

2016-01-12 13:09:19 [6@VS-GLPI]
  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 4
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  :                                                  plugin_genericobject_getDropdown()
  inc\plugin.class.php:1166                          call_user_func()
  inc\plugin.class.php:1181                          Plugin::doOneHook()
  inc\dropdown.class.php:858                         Plugin::getDropdowns()
  inc\commondropdown.class.php:108                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1283                            CommonDropdown::getMenuContent()
  front\central.php:72                               Html::header()

**Comment by dethegeek** [comment]
Hi

I think the error you encounteer in the preg_replace() function may be triggered by a root path very specific to your environment.

Can you open a session in GLPI with a super admin user, go in Setup > General > tab System, and tell the root path of GLPI (found below ```Information about system installation and configuration ```) ?

I guess you may have backslaskes and/or dollar symbol, followed by a number

**Comment by janpieters74** [comment]
Dear
I do not find any parameter about the root path on that page (PS: I use a Windows OS):


Informatie installatie en configuratie van het systeem
[code]
 
GLPI 0.90.1 ( => D:\glpi)

Server
 
Operating system: Windows NT VS-GLPI 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586
PHP 5.6.16 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, calendar, cgi-fcgi, ctype, curl, date, dom, ereg,
	exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli,
	mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, pdo_sqlsrv, session, soap, sqlsrv, standard, tidy, tokenizer, wddx, xml,
	xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/7.5
	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.6.10-log
	Server SQL Mode: STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
OKD:\glpi/config : OK
OKD:\glpi/files : OK
OKD:\glpi/files/_dumps : OK
OKD:\glpi/files/_sessions : OK
OKD:\glpi/files/_cron : OK
OKD:\glpi/files/_graphs : OK
OKD:\glpi/files/_lock : OK
OKD:\glpi/files/_plugins : OK
OKD:\glpi/files/_tmp : OK
OKD:\glpi/files/_rss : OK
OKD:\glpi/files/_uploads : OK
OKD:\glpi/files/_pictures : OK
OKD:\glpi/files/_log : OK

Libraries
 
htmLawed version 1.1.20 in (D:\glpi\lib\htmlawed)
phpCas version 1.3.4 in (D:\glpi\lib\phpcas)
PHPMailer version 5.2.8 in (D:\glpi\lib\phpmailer)
ZetaComponent ezcGraph installed in (D:\glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (D:\glpi\lib\Zend)
SimplePie version 1.3.1 in (D:\glpi\lib\simplepie)
TCPDF version 6.2.12 in (D:\glpi\lib\tcpdf)
ircmaxell/password-compat in (D:\glpi\lib\password_compat). Compatitility: Ok

LDAP directories
 
Server: 'LDAP1.woonhaven.local', Port: '389', BaseDN: 'OU=Locations,OU=Users,OU=Woonhaven,DC=woonhaven,DC=local', Connection
		filter: '(objectClass=user)', RootDN: 'CN=TA GLPI,OU=Technical,OU=Users,OU=Woonhaven,DC=woonhaven,DC=local', Use TLS: none
Server: 'LDAP1.woonhaven.local', Port: '389', BaseDN: 'OU=Functional Mailboxes,OU=Users,OU=Woonhaven,DC=woonhaven,DC=local',
		Connection filter: '(objectClass=user)', RootDN: 'CN=TA GLPI,OU=Technical,OU=Users,OU=Woonhaven,DC=woonhaven,DC=local', Use TLS:
		none

Mysql replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@10.139.20.53)

Mails receivers
 
Name: 'WHA Exchange' Active: Yes
	Server: '{10.139.20.53/imap/novalidate-cert/notls}' Login: 'woonhaven\helpdesk' Password: Yes

Plugins list
 
	datainjection        Name: File injection                 Version: 2.4.1      State: Enabled
	genericobject        Name: Objects management             Version: 0.85-1.0   State: Enabled
	simcard              Name: Sim cards management           Version: 1.4.1      State: Enabled

[/code]

**Comment by wawax** [comment]
Can you try with the master version ? We made some fixes that could fix your issue

**Comment by trasher** [comment]
This issue should be fixed in the latest release (0.85-1.1). Feel free to reopen the ticket if the problem still persists.
