### ISSUE TITLE
objects linkeable to another objects

### ISSUE THREAD

**Issue by camilocorrea** [pluginsGLPI/genericobject#73]
There's a way to make objects depends from another objects, for example: a car have engine, wheels, etc...

**Comment by Manu1400** [comment]
FYI : Pull request in the next week for add this feature in genericobject.

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
