### ISSUE TITLE
Create multi select field associated to an object

### ISSUE THREAD

**Issue by mladengeorgiev** [pluginsGLPI/genericobject#76]
Hello,
I have created a custom object called 'Service'. I want to associate the service to multiple services. Can I create select field? Maybe something like the attached screenshot?
![glpi](https://cloud.githubusercontent.com/assets/16850788/12529786/af6729e4-c1cd-11e5-92d4-dccc5f7c9fa6.png)

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
