### ISSUE TITLE
0.85-1.0 &.GLPI 0.90 / 0.90.1: constant-files are not included

### ISSUE THREAD

**Issue by spidergen** [pluginsGLPI/genericobject#78]
The constant-files for creating custom filed types could not be included. I had to change the $file creation in the "includeConstants" function in .\inc\type.class.php:

Before:
$file = GENERICOBJECT_FIELDS_PATH . "/$name.constant.php";

After:
$file = GLPI_ROOT . "/plugins/genericobject/fields/$name.constant.php";

After that it works.

**Comment by dvinouze** [comment]
Hi,
If your filed type name is "cars", you will have to create this /var/www/glpi/files/_plugins/genericobject/fields/cars.constant.php and it works.

The location of GENERICOBJECT_FIELDS_PATH is GLPI_ROOT . "files/_plugins/genericobject/fields/"

**Comment by LR69** [comment]
Hi,

I thought the $name.constant.php file had to be created in <GLPI_ROOT>/plugins/genericobject/fields/constants/, as indicated in the [wiki](file:///C:/Users/LR/Desktop/generic%20object%20manual/0.85%202.x%20manual%20%C2%B7%20TECLIB_genericobject%20Wiki%20%C2%B7%20GitHub.htm).
Obviously it's not the case anymore. Do you know if there is an up to date procedure to create new fields with genericobject ?

**Comment by spidergen** [comment]
Thanks guys! You're both are right.

The wiki seems not to be up to date. I thought the "/plugins/genericobject/fields/" should be the correct one, but GENERICOBJECT_FIELDS_PATH is GLPI_ROOT . "files/_plugins/genericobject/fields/"  should be that one.

I reverted my change from Comment #1 and moved the files to "glpi/files/_plugins/genericobject/fields/" and it works without doing modifications to ".\inc\type.class.php"

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
