### ISSUE TITLE
GLPI 0.85.5 : Unable to add software version

### ISSUE THREAD

**Issue by ThomasTerrier** [pluginsGLPI/genericobject#79]
Hello, 

I have a profile named "Correspondant Site".

In GenericObject I have a category named "System" . The profile "Correspondant Site" has the rights in Reading on the System category .

When I 'm on a software, I can't add new versions , the page appears but without content.

When I wish to withdraw a license to a PC, the error message "enabling error" appears .

When I disable the plugin GenericObject , everything works fine .

If I add all the rights to the profile "Correspondant Site" on the System category , everything works fine . However, this is not possible within my organization.

If necessary , I could provide screenshot.

Sorry for my bad English. 

Thank's in Advance,

**Comment by nsautier** [comment]
hello,
meme type de probleme pour la partie helpdesk ici :
https://github.com/TECLIB/genericobject/issues/66
le comportement de glpi redevient normal lorsqu'on  desactive le plugins

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
