### ISSUE TITLE
Upgradation to 0.85-1.0 fails

### ISSUE THREAD

**Issue by ask2me007** [pluginsGLPI/genericobject#82]
Iam trying to upgrade my glpi  0.84 version to glpi 0.91.1 . Every thing was fine up to upgrading the GLPI.
But I cannot upgrade the plugin generic object 0.85 . Iam trying this many times since last one month. Tried with different machines but every time fails. Iam also attaching the error message seen in the logs(sql-error)
Please help me to resolve this issues.
## lang.reservation.itemtype## : ##reservation.itemtype

 ##lang.reservation.item## : ##reservation.item##

 ##reservation.url##

 ##ENDFOREACHreservations##\',\'&lt;p&gt;##lang.reservation.entity## : ##reservation.entity## &lt;br /&gt; &lt;br /&gt;
## FOREACHreservations## &lt;br /&gt;##lang.reservation.itemtype## :  ##reservation.itemtype##&lt;br /&gt;

Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''&lt;p&gt;##lang.reservation.entity## : ##reservation.entity## &lt;br /&gt; &lt;' at line 1
Backtrace :
/var/www/html/glpi/front/backup.php&nbsp;:286           DBmysql->query()
/var/www/html/glpi/front/backup.php&nbsp;:564           restoreMySqlDump()
/var/www/html/glpi/front/backup.php

2016-01-31 19:46:39
**\* MySQL query error:

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
