### ISSUE TITLE
Authorization issue while using the plugin with 0.90.1

### ISSUE THREAD

**Issue by Giudy** [pluginsGLPI/genericobject#85]
Hi, 
I've experienced this weird behavior of GLPI while using this plugin.
Profiles are unable to reassign tickets and to link tikects to change/problems... if they don't have full permissions on objects even if the objects do not have any relation with the actions.

one set the permissions, everything goes fine.

**Comment by guilhermestella** [comment]
I've experienced it too. In my ocasion i can CRUD and ticket model but i cant add/remove a required/hidden/predefined field.

I temporarily solved the problem by giving full permission to the user's profile.

**Comment by onedmgoflthl** [comment]
Same here, thanks for clarifying. It was quite a problem.

**Comment by eduardospinola** [comment]
Same problem here. 
When I put read, update, create, and delete permissions, on the last object created in the plugin, the group and user assignments start working again.

**Comment by eduardospinola** [comment]
Same problem in glpi 9.1.x

**Comment by eduardospinola** [comment]
I am also unable to exclude a technical group from the ticket. Neither with technical profile nor with superadmin.

**Comment by GonzElo** [comment]
Is there any known way to avoid these secondary effect on Authorizations? 
I have been waiting some time to see if there is any update.

Among other unwanted effects for me is that I cannot add Notes on any asset when this Plugin is active. Always returning: You don't have permission to perform this action.

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
