### ISSUE TITLE
TCPDF ERROR: Some data has already been output, can't send PDF file

### ISSUE THREAD

**Issue by Lynxweb** [pluginsGLPI/genericobject#87]
Hi,

I've an error message when I try to print a list (ie my tickets) : 

"**TCPDF ERROR: Some data has already been output, can't send PDF file**"

I checked log file & it seems that problem is Generic Object plugin.
Here my config : 

**GLPI 0.85.4
Plugin 0.85 - GPLv3+**

Here log file : 

-------------------------------------------------------------------------------------------------------------------------
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\object.class.php:191     _log()
  plugins\genericobject\inc\object.class.php:241     PluginGenericobjectObject::getMenuIcon()
  inc\html.class.php:1198                            PluginGenericobjectObject::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\object.class.php:191     _log()
  plugins\genericobject\inc\object.class.php:241     PluginGenericobjectObject::getMenuIcon()
  inc\html.class.php:1198                            PluginGenericobjectObject::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\object.class.php:191     _log()
  plugins\genericobject\inc\object.class.php:241     PluginGenericobjectObject::getMenuIcon()
  inc\html.class.php:1198                            PluginGenericobjectObject::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\object.class.php:191     _log()
  plugins\genericobject\inc\object.class.php:241     PluginGenericobjectObject::getMenuIcon()
  inc\html.class.php:1198                            PluginGenericobjectObject::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\inc\object.class.php:191     _log()
  plugins\genericobject\inc\object.class.php:241     PluginGenericobjectObject::getMenuIcon()
  inc\html.class.php:1198                            PluginGenericobjectObject::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  :                                                  plugin_genericobject_getDropdown()
  inc\plugin.class.php:1162                          call_user_func()
  inc\plugin.class.php:1177                          Plugin::doOneHook()
  inc\dropdown.class.php:873                         Plugin::getDropdowns()
  inc\commondropdown.class.php:104                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1198                            CommonDropdown::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  :                                                  plugin_genericobject_getDropdown()
  inc\plugin.class.php:1162                          call_user_func()
  inc\plugin.class.php:1177                          Plugin::doOneHook()
  inc\dropdown.class.php:873                         Plugin::getDropdowns()
  inc\commondropdown.class.php:104                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1198                            CommonDropdown::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  :                                                  plugin_genericobject_getDropdown()
  inc\plugin.class.php:1162                          call_user_func()
  inc\plugin.class.php:1177                          Plugin::doOneHook()
  inc\dropdown.class.php:873                         Plugin::getDropdowns()
  inc\commondropdown.class.php:104                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1198                            CommonDropdown::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  :                                                  plugin_genericobject_getDropdown()
  inc\plugin.class.php:1162                          call_user_func()
  inc\plugin.class.php:1177                          Plugin::doOneHook()
  inc\dropdown.class.php:873                         Plugin::getDropdowns()
  inc\commondropdown.class.php:104                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1198                            CommonDropdown::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  :                                                  plugin_genericobject_getDropdown()
  inc\plugin.class.php:1162                          call_user_func()
  inc\plugin.class.php:1177                          Plugin::doOneHook()
  inc\dropdown.class.php:873                         Plugin::getDropdowns()
  inc\commondropdown.class.php:104                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1198                            CommonDropdown::getMenuContent()
  front\ticket.php:41                                Html::header()
2015-12-07 15:59:20 [1188@SUPPORT]
  *** PHP Warning(2): preg_replace() [<a href='function.preg-replace'>function.preg-replace</a>]: Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  :                                                  plugin_genericobject_getDropdown()
  inc\plugin.class.php:1162                          call_user_func()
  inc\plugin.class.php:1177                          Plugin::doOneHook()
  inc\dropdown.class.php:873                         Plugin::getDropdowns()
  inc\commondropdown.class.php:104                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1198                            CommonDropdown::getMenuContent()
  front\ticket.php:41                                Html::header()

-------------------------------------------------------------------------------------------------------------------------

Do you have any idea about this issue ?

Thank you
Yacine

**Comment by Lynxweb** [comment]
up !!
Are you ok guys ?

**Comment by wawax** [comment]
are you on linux or windows ?

**Comment by Lynxweb** [comment]
Windows

**Comment by wawax** [comment]
can you retest with the current master branch ?

**Comment by Lynxweb** [comment]
What is "the current master branch" ?





2016-08-20 11:30 GMT+02:00 Walid Nouh <notifications@github.com>:

**Comment by wawax** [comment]
it's the plugin as it it in the directory, with my last commits

**Comment by trasher** [comment]
The issue should be resolved in the latest release (0.85-1.1). Feel free to repoen the ticket if problem still persists.
