### ISSUE TITLE
problem when instal Gestion d'objets

### ISSUE THREAD

**Issue by xhamzao** [pluginsGLPI/genericobject#88]
when I install the Gestion d'objets i see this msg in the blanc page :

Work in progress...
Valeur par défaut invalide pour 'date_mod'

what must i do to solve this prob ???

**Comment by wawax** [comment]
please give us : 
- GLPi version
- Plugin version
- OS : Linux / Windows
- OS Version

Please also copy/paste debug info (between [code] [/code]) in Setup > General > System tab.

**Comment by trasher** [comment]
Mandatory informations are still missing. Please test with latest plugin release, and feel free to reopen the ticket if the problem still persists.
