### ISSUE TITLE
ERROR 500 - INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by jmcatellani** [pluginsGLPI/genericobject#90]
Hello, just installed GLPI 0.90.2 and me selling the 500 error.

I raised the service provider hostgator hosting.
Can it be?

**Comment by trasher** [comment]
I'm confused... Is your question related to this plugin or to GLPi?

I'm closing this issue, please open a ticket against GLPi is this is not related to the plugin, feel free to reopen with additional data if not.

Anyways, you'll have to provide the contents of the logs file.
