### ISSUE TITLE
Problems with reservations.

### ISSUE THREAD

**Issue by dmartinezgomez** [pluginsGLPI/genericobject#91]
I`m trying to configure custom items, in this case rooms, It should be reservable but I cant do it accesible for self-Service.

Everything it's ok for other users, but self.service users cannot reserve rooms.

I'm using a local fresh install of **GLPI 0.90.3** and  **Objects management    0.85-1.0**.

I've tried to fix it with #57 and #9 unsuccessfully.

My glpi_reservations is empty, and glpi_reservationitems only has tree items:

id      itemtype                                    entities_id     is_recursive    items_id    comment     is_active   is_deleted
1   PluginGenericobjectSala             0   0   1   NULL    1   0
2   Computer                            0   0   1   NULL    1   0
3   PluginGenericobjectPrueba   0   0   1   NULL    1   0

Only computer is shown in self-service reservations list.

any ideas?

Thanks.

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
