### ISSUE TITLE
Add a simple dropdown field

### ISSUE THREAD

**Issue by dvinouze** [pluginsGLPI/genericobject#93]
Hi,
I want to add a simple dropdown field ; I follow the wiki but it doesn't work.
when I replace this
```php
$GO_FIELDS['plugin_genericobject_mytypecolors_id']['name']       = $LANG['genericobject']["<type's name>"][2];
$GO_FIELDS['plugin_genericobject_mytypecolors_id']['field']      = 'color';
$GO_FIELDS['plugin_genericobject_mytypecolors_id']['input_type'] = 'dropdown';
```
by adding the keyword **types** between **mytypecolors** and **_id** to the name and the input type ; it works fine
```php
$GO_FIELDS['plugin_genericobject_mytypecolorstypes_id']['name']       = 'My Color';
$GO_FIELDS['plugin_genericobject_mytypecolorstypes_id']['input_type'] = 'dropdown';
```
Is it a nice solution to add a dropdown field ?
Thanks

**Comment by nqb** [comment]
Exactly same issue.

If I follow documentation, I can add a dropdown field to my object but I can't add choices for my dropdown.

**Comment by jmreymond** [comment]
name too long ?
There is a limitation in mysql, try with a shorter identifiant

**Comment by glasnosh** [comment]
Same issue for me (GLPI 0.90.3 and plugin from 'Master Branch'). It's a random behavior that I can't reproduce 100%, but it looks to be related with adding dropdown fields to _"field.constant.php"_ after adding new defined-assets' items.
For example, I add this content to _"field.constant.php"_:

```
$GO_FIELDS['mytypeanho3_id']['name']       = 'Anho3';
$GO_FIELDS['mytypeanho3_id']['field']      = 'anho3';
$GO_FIELDS['mytypeanho3_id']['input_type'] = 'dropdown';

```
Then:
I add the new field to a previously defined asset type (_vg.-Aircraft_) which already have discrete assets (_vg.-Spitfire, P51..._). When I try to create new dropdown items for the _"Anho3"_ field (_vg.-1935, 1936..._) I can see the form for doing it and enter the text in the textbox, but the 'insert' button is missing.

If I define every dropdown field before adding the discrete assets, It looks to work propertly, but this is a lottery. It is necesary for me to add new fields over time.

**dvinouze**, your workarround works perfectly. Defining the new dropdown field as:
```
$GO_FIELDS['mytypeanho3types_id']['name']       = 'Anho3';
$GO_FIELDS['mytypeanho3types_id']['field']      = 'anho3';
$GO_FIELDS['mytypeanho3types_id']['input_type'] = 'dropdown';
```
...the behaviour is correct everytime a try (~15 times this morning).

**Comment by glasnosh** [comment]
Taking a look to sql logfile and mysql tablespace it looks to be a problem with table naming. When you create a new dropdown field, for example: 
```
$GO_FIELDS['mytypeanho4_id']['name']       = 'Anho4';
$GO_FIELDS['mytypeanho4_id']['field']      = 'anho4';
$GO_FIELDS['mytypeanho4_id']['input_type'] = 'dropdown';
```
The plugin creates a new table called _'glpi_plugin_genericobject_mytypeanho4s'_, adding an extra 's'. If I add the new dropdown field to the defined assets and then I try to see the fields preview for the new asset definition, I get this in _glpi/files/_log/sql-errors.log_


```
016-07-13 14:41:03 [2@FCSCL-S037]
  *** MySQL query error:
  SQL: SHOW COLUMNS FROM `glpi_plugin_genericobject_mytypeanho4`
  Error: Table 'glpi.glpi_plugin_genericobject_mytypeanho4' doesn't exist
  Backtrace :
  inc/dbmysql.class.php:374                          
  inc/commondbtm.class.php:289                       DBmysql->list_fields()
  inc/commondbtm.class.php:2553                      CommonDBTM->getEmpty()
  plugins/genericobject/inc/object.class.php:527     CommonDBTM->isEntityAssign()
  plugins/genericobject/inc/object.class.php:473     PluginGenericobjectObject->displayField()
  plugins/genericobject/inc/object.class.php:719     PluginGenericobjectObject->showForm()
  plugins/genericobject/inc/type.class.php:157       PluginGenericobjectObject::showPrevisualisationForm()
  inc/commonglpi.class.php:469                       PluginGenericobjectType::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
2016-07-13 14:41:03 [2@FCSCL-S037]
 
```
It is trying to query a nonexistent table, because probably this was not propertly created (an extra 's' in the name).

I think the behaviour depends of the name used to define the field in _field.constant.php_ . Probably that is the reason why the workarround proposed by dvinouze works. Taking a look to the code (I'm not a PHP coder), the problem could be in the file _inc/field.class.php_ and somewhere of this function 
```
public static function addNewField($table, $field, $after=false)
[...]
if ($table != '' && !TableExists($table)) {
            //Cannot use standard methods because class doesn't exists yet !
            $name = str_replace("glpi_plugin_genericobject_","", $table);
            $name = getSingular($name);
[...]
```

**Comment by wawax** [comment]
Hello,

The glpi framework requires your first (which is a foreign key) to end with s_id
In your case, your object muste be mytypeanho4s_id instead of mytypeanho4_id

Can you try that ?

**Comment by glasnosh** [comment]
Thank you so much wawax. That works perfectly. Definitive solution. It also explain why dvinouze's workaround works.
A good topid to add to the manual maybe.

Thanks again.

**Comment by nqb** [comment]
> A good topid to add to the manual maybe.

@glasnosh : done in [GLPI plugins documentation](http://glpi-plugins.readthedocs.io/en/latest/genericobject/index.html#define-biomedical-s-new-fields).
