### ISSUE TITLE
Update error 0.8 to 0.9

### ISSUE THREAD

**Issue by ychoucha** [pluginsGLPI/genericobject#95]
Hello well i m triyng to update but i have this error when i lunche the database update : 

Traitement en cours...
Invalid default value for 'date_mod'

**Comment by dethegeek** [comment]
Hi

Did you enable strict mode in Mysql / MariaDB ?

**Comment by ychoucha** [comment]
i do it with this --> http://www.mavengineering.com/blog/2012/12/06/turning-on-strict-mode-for-mysql-installed-with-homebrew/

and now i have this message : 

Changement de la structure de la base de données - glpi_plugin_genericobject_types (1 seconde)

**Comment by dethegeek** [comment]
Oh, sorry, I just wanted to know if you enabled it someday. I did not asked you to enable it. 

Please, revert your change, and simply use the last command of your resource to check if strict mode is still enabled or not.

**Comment by ychoucha** [comment]
ok now i have this :+1: 

Traitement en cours...


and nothing come??

**Comment by dethegeek** [comment]
Ok, 

First have a look in php_errors.log in your GLPI instance. I thijnk there is a backtrace of the error 
``` Invalid default value for 'date_mod' ```

About the latest one, I guess you issued a 500 internal server error. You'll certainly find a entry in your HTTP server logs.

Please provide them both.

Note : before updating GLPI or any plugin, you should always do a backup, and restore it if you need to retry a failed upgrade. This is because your first try probably left the plugin state in an inconsistent state,

**Comment by ychoucha** [comment]
i found this : 


```
[Fri May 20 12:34:24.429718 2016] [core:notice] [pid 20040] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 20 12:52:49.062241 2016] [:error] [pid 20055] [client 192.168.17.251:54369] PHP Fatal error:  Uncaught Error: Class 'PluginGenericobjectBorneseV01' not found in /var/www/html/glpi/plugins/genericobject/inc/type.class.php:1822\nStack trace:\n#0 /var/www/html/glpi/plugins/genericobject/hook.php(118): PluginGenericobjectType::install(Object(Migration))\n#1 /var/www/html/glpi/inc/plugin.class.php(643): plugin_genericobject_install()\n#2 /var/www/html/glpi/front/plugin.form.php(49): Plugin->install('40')\n#3 {main}\n  thrown in /var/www/html/glpi/plugins/genericobject/inc/type.class.php on line 1822, referer: http://192.168.17.48/glpi/front/plugin.php
```

for error  : 

Changement de la structure de la base de données - glpi_plugin_genericobject_types (1 seconde)

![glpiplugingenericobjecterror](https://cloud.githubusercontent.com/assets/301074/15533826/86762590-2266-11e6-921f-60eca958c9a3.jpg)

what i can do please ?
i m stuck with this to finalise my update

**Comment by ychoucha** [comment]
and this error blocked GLPI, no way to login :/

ic'ant found error in log : 

`Utilisation invalide de l'identifiant de session`

**Comment by btry** [comment]
Hi

Can you check if the file ```PluginGenericobjectBorneseV01.class.php``` exists and the webserver has permissions to read it ? It should be located  in ```/var/www/html/glpi/files/_plugins/genericobject/inc/```

**Comment by trasher** [comment]
Duplicates #68
