### ISSUE TITLE
Difference between zip and tar archive

### ISSUE THREAD

**Issue by nqb** [pluginsGLPI/genericobject#98]
Hello,
```
[~]: unzip -l genericobject-0.85-1.0.zip | head -n4
Archive:  genericobject-0.85-1.0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2015-09-30 16:07   genericobject/
[~]: tar t -zf genericobject-0.85-1.0.tar.gz | head -n1
genericobject-0.85-1.0/
```
`genericobject-0.85-1.0/` should be `genericobject/` in tar archive.

**Comment by trasher** [comment]
I guess this is github features that are confusing.

You got 2 "source code" (one for a zip file, the other for a tar file) links - which are *not* the official releases; those files are generated by github, I do no think we can change them.

The official release is the one named "genericobject-{version}"; which have the correct names :)
