### ISSUE TITLE
A notification template traslation form!

### ISSUE THREAD

**Issue by okvok** [pluginsGLPI/genericobject#99]
Hi!
I've got an issue in glpi v0.90.3 with a notification template traslation form. While this plugin is enable a notification template traslation form does not work properly. And the second problem is associate with user's including in profiles or groups as well. When I am trying to icnlude some user into a group or profile then the message "You don't have permission to perform this action." appears.
Does anybody know how to solve these both issues?

PS: sorry for my bad English.

**Comment by stonebuzz** [comment]
This issue has not changed for a long time.
I am closing this issue, feel free to continue the discussion here if you want or to reopen it if the problem or your request is still present (with the latest version) .

Best regards
